// Map audit findings (selectors + text) back to source files. Pure Node, no browser.
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, extname, relative } from "node:path";

const SOURCE_EXT = new Set([".jsx", ".tsx", ".js", ".ts", ".vue", ".svelte", ".astro", ".html", ".php", ".liquid", ".twig", ".erb", ".hbs", ".css", ".scss", ".mdx"]);
const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", ".next", ".nuxt", ".output", ".svelte-kit", "coverage", "vendor", ".vercel", ".netlify", "out"]);

/** Recursively list source files under dir. */
export function listSourceFiles(dir, max = 5000) {
  const out = [];
  const walk = (d) => {
    if (out.length >= max) return;
    let entries;
    try {
      entries = readdirSync(d);
    } catch {
      return;
    }
    for (const name of entries) {
      if (SKIP_DIRS.has(name) || name.startsWith(".")) continue;
      const p = join(d, name);
      let st;
      try {
        st = statSync(p);
      } catch {
        continue;
      }
      if (st.isDirectory()) walk(p);
      else if (SOURCE_EXT.has(extname(name)) && st.size < 800_000 && !/\.min\.|audit\.browser\.js$/.test(name)) out.push(p);
    }
  };
  walk(dir);
  return out;
}

/**
 * Parse an audit item like `div > button.flex.items-center 54×19 "Définir"` into
 * { tag, classes, text }. Class names generated by CSS-in-JS/hashes are ignored.
 */
export function parseItem(item) {
  const text = (item.match(/"([^"]{2,40})"/) || [])[1];
  const selPart = item.split(/\s(?=\d+×\d+|\(|")/)[0];
  const last = selPart.split(" > ").pop().trim();
  const [tag, ...classes] = last.split(".");
  return {
    tag: /^[a-z][a-z0-9-]*$/.test(tag) ? tag : undefined,
    classes: classes.filter((c) => c && !/^(css|sc|jsx|svelte)-|[A-Z0-9]{6,}/.test(c)),
    text: text && text.replace(/[·•→↑↓]/g, "").trim(),
  };
}

/** Find lines matching an item: text first (most specific), then all classes on one line. */
export function findInSources(files, item, cache = new Map()) {
  const { classes, text } = parseItem(item);
  const hits = [];
  const read = (f) => {
    if (!cache.has(f)) cache.set(f, readFileSync(f, "utf8").split("\n"));
    return cache.get(f);
  };
  for (const f of files) {
    const lines = read(f);
    lines.forEach((line, i) => {
      let score = 0;
      if (text && text.length >= 3 && line.includes(text)) score += 3;
      if (classes.length >= 2 && classes.every((c) => line.includes(c))) score += classes.length;
      if (score >= 2) hits.push({ file: f, line: i + 1, score, snippet: line.trim().slice(0, 140) });
    });
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, 3);
}

/** Where the root font-size is set (for the root-font-size finding). */
export function findRootFontSize(files) {
  const hits = [];
  for (const f of files.filter((x) => /\.(css|scss|html)$/.test(x) || /tailwind\.config/.test(x))) {
    const lines = readFileSync(f, "utf8").split("\n");
    lines.forEach((line, i) => {
      if (/(^|[\s,{])(html|:root)\b[^{]*\{[^}]*font-size|^\s*font-size:\s*(15|14|17|18)px|fontSize.*html/i.test(line)) hits.push({ file: f, line: i + 1, snippet: line.trim().slice(0, 140) });
    });
    // multi-line html { … font-size … } blocks
    const src = lines.join("\n");
    for (const m of src.matchAll(/(html|:root)\s*\{[^}]*font-size:[^;]+;/g)) {
      const line = src.slice(0, m.index).split("\n").length;
      if (!hits.some((h) => h.file === f && Math.abs(h.line - line) < 5)) hits.push({ file: f, line, snippet: m[0].replace(/\s+/g, " ").slice(0, 140) });
    }
  }
  return hits;
}

/** Locate every finding item of an audit result in the source tree. */
export function locate(result, srcDir) {
  const files = listSourceFiles(srcDir);
  const cache = new Map();
  return result.findings.map((f) => ({
    rule: f.rule,
    severity: f.severity,
    message: f.message,
    locations:
      f.rule === "root-font-size"
        ? findRootFontSize(files)
        : f.items.map((item) => ({ item, hits: findInSources(files, item, cache) })),
    relativeTo: srcDir,
  }));
}

export function formatLocations(located, cwd = process.cwd()) {
  const out = [];
  for (const f of located) {
    out.push(`${f.severity === "error" ? "✗" : f.severity === "warn" ? "!" : "·"} [${f.rule}] ${f.message}`);
    if (f.rule === "root-font-size") {
      for (const h of f.locations) out.push(`    → ${relative(cwd, h.file)}:${h.line}  ${h.snippet}`);
      if (!f.locations.length) out.push("    → not found in CSS: check the global stylesheet or a font-size set from JS");
      continue;
    }
    for (const { item, hits } of f.locations) {
      out.push(`    ${item}`);
      for (const h of hits) out.push(`      → ${relative(cwd, h.file)}:${h.line}  ${h.snippet}`);
      if (!hits.length) out.push("      → no match (dynamic class names or text from data)");
    }
  }
  return out.join("\n");
}
