// ui-ux-glowup — in-browser audit. GENERATED by build-browser-audit.mjs, do not edit.
// Paste into the DevTools console of the page to audit (works on logged-in pages).
// Audits the current viewport only: run it once at desktop width and once with the
// device toolbar at 390px to get the mobile checks.
// Returns { report, result } and prints the report.
(() => {
// ---- lib/color.mjs ----
// Pure color utilities (no browser needed). Colors are [r, g, b, a] with r,g,b in 0-255 and a in 0-1.

/** Composite a (possibly translucent) foreground over an opaque background. */
function composite(fg, bg) {
  const a = fg[3] ?? 1;
  return [
    Math.round(fg[0] * a + bg[0] * (1 - a)),
    Math.round(fg[1] * a + bg[1] * (1 - a)),
    Math.round(fg[2] * a + bg[2] * (1 - a)),
    1,
  ];
}

/**
 * Resolve the effective opaque background from a stack of layers,
 * ordered from the element itself up to the root. Falls back to white.
 */
function flattenBackground(layers, fallback = [255, 255, 255, 1]) {
  let result = fallback;
  for (let i = layers.length - 1; i >= 0; i--) {
    const layer = layers[i];
    if (!layer || layer[3] === 0) continue;
    result = composite(layer, result);
  }
  return result;
}

/** WCAG 2.x relative luminance. */
function luminance([r, g, b]) {
  const lin = (c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

/** WCAG 2.x contrast ratio between two opaque colors, rounded to 2 decimals. */
function contrastRatio(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la > lb ? [la, lb] : [lb, la];
  return Math.round(((hi + 0.05) / (lo + 0.05)) * 100) / 100;
}

/** WCAG large text: >= 24px, or >= 18.66px (14pt) and bold (>= 700). */
function isLargeText(fontSizePx, fontWeight) {
  return fontSizePx >= 24 || (fontSizePx >= 18.66 && Number(fontWeight) >= 700);
}

/** Minimum AA ratio for a given text size / weight. */
function requiredRatio(fontSizePx, fontWeight) {
  return isLargeText(fontSizePx, fontWeight) ? 3 : 4.5;
}

function toHex([r, g, b]) {
  return "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
}

// ---- lib/analyze.mjs ----
// Pure analysis of data collected by probe.mjs. No browser needed — fully unit-testable.

const CRITERIA = ["Hierarchy", "Typography", "Spacing", "Components", "Visuals", "Content", "Responsive", "Accessibility"];

const PENALTY = { error: 1, warn: 0.5, info: 0 };

/** Group numbers and return [value, count] sorted by count desc. */
function histogram(values, round = (v) => v) {
  const map = new Map();
  for (const v of values) {
    const k = round(v);
    map.set(k, (map.get(k) || 0) + 1);
  }
  return [...map.entries()].sort((a, b) => b[1] - a[1]);
}

/** A spacing value is on-grid if it's a multiple of 4px, or of 2px below 16px (half steps like 6px, 10px). */
function onGrid(v) {
  const step = v < 16 ? 2 : 4;
  return Math.abs(v / step - Math.round(v / step)) < 0.01;
}

/** Share of spacing values (>= 2px) that sit on the grid. */
function gridConformity(values) {
  const relevant = values.filter((v) => v >= 2);
  if (!relevant.length) return 1;
  return relevant.filter(onGrid).length / relevant.length;
}

/** Most common paragraph font size, falling back to the most common non-heading text size. */
function bodyFontSize(data) {
  const para = histogram(data.paragraphs.map((p) => p.fontSize), Math.round);
  if (para.length) return para[0][0];
  const texts = histogram(data.texts.filter((t) => !/^h[1-6]$/.test(t.tag)).map((t) => t.fontSize), Math.round);
  return texts.length ? texts[0][0] : 16;
}

/** Contrast failures for collected text nodes. Skips text over background images (unknowable). */
function contrastIssues(texts) {
  const seen = new Set();
  const out = [];
  for (const t of texts) {
    if (t.bgImage || !t.fontSize) continue;
    const bg = flattenBackground(t.bgLayers);
    const fg = composite(t.color, bg);
    const ratio = contrastRatio(fg, bg);
    const need = requiredRatio(t.fontSize, t.fontWeight);
    const key = t.sel + "|" + ratio;
    if (ratio < need && !seen.has(key)) {
      seen.add(key);
      out.push({ sel: t.sel, text: t.text, ratio, required: need });
    }
  }
  return out.sort((a, b) => a.ratio - b.ratio);
}

/** Produce findings from desktop + mobile page data. */
function analyze(desktop, mobile) {
  const findings = [];
  const add = (criterion, severity, rule, message, items = []) =>
    findings.push({ criterion, severity, rule, message, items: items.slice(0, 8), count: items.length || undefined });

  const d = desktop;
  const m = mobile || desktop;

  // ---------- Hierarchy ----------
  const h1s = d.headings.filter((h) => h.level === 1);
  if (h1s.length === 0) add("Hierarchy", "error", "h1-missing", "No <h1> on the page.");
  if (h1s.length > 1) add("Hierarchy", "warn", "h1-multiple", `${h1s.length} <h1> elements; use one per page.`, h1s.map((h) => h.text));
  const bodySize = bodyFontSize(d);
  if (h1s[0] && h1s[0].fontSize / bodySize < 1.8)
    add("Hierarchy", "warn", "h1-weak", `<h1> is only ${(h1s[0].fontSize / bodySize).toFixed(1)}× body size (${h1s[0].fontSize}px vs ${bodySize}px). Aim for 2.5× or more on landing pages.`);

  // ---------- Typography ----------
  const families = histogram(d.texts.map((t) => t.fontFamily)).filter(([f]) => !/mono|courier|consolas|menlo/i.test(f));
  if (families.length > 2) add("Typography", "warn", "font-families", `${families.length} font families in use; keep to 2.`, families.map(([f, c]) => `${f} (${c})`));
  const sizes = histogram(d.texts.map((t) => t.fontSize), (v) => Math.round(v));
  if (sizes.length > 10) add("Typography", "warn", "type-scale", `${sizes.length} distinct font sizes; use a tighter type scale (≈ 6–9 steps).`, sizes.map(([s, c]) => `${s}px ×${c}`));
  const tightBody = d.paragraphs.filter((p) => p.fontSize < 24 && p.lineHeight && p.lineHeight / p.fontSize < 1.4);
  if (tightBody.length) add("Typography", "warn", "line-height", "Paragraph line-height below 1.4.", tightBody.map((p) => `${p.sel} (${(p.lineHeight / p.fontSize).toFixed(2)})`));
  const wide = d.paragraphs.filter((p) => p.measure > 85);
  if (wide.length) add("Typography", "warn", "measure", "Lines longer than ~85 characters; cap paragraphs around 65ch.", wide.map((p) => `${p.sel} (~${p.measure}ch)`));
  const looseHeadings = d.headings.filter((h) => h.fontSize >= 32 && h.letterSpacing >= 0);
  if (looseHeadings.length)
    add("Typography", "info", "heading-tracking", "Large headings with default tracking; -0.02em to -0.04em usually reads more refined.", looseHeadings.map((h) => `${h.text} (${h.fontSize}px)`));

  // ---------- Spacing ----------
  const conformity = gridConformity(d.spacing);
  const offGrid = histogram(d.spacing.filter((v) => v >= 2 && !onGrid(v)));
  const root = d.rootFontSize || 16;
  if (root !== 16) {
    const fractional = d.spacing.filter((v) => !Number.isInteger(v)).length / (d.spacing.length || 1);
    add(
      "Spacing",
      fractional > 0.3 ? "error" : "warn",
      "root-font-size",
      `Root cause: <html> font-size is ${root}px instead of 16px, so every rem value (Tailwind spacing, text sizes, radii) is scaled by ${(root / 16).toFixed(4)} and ${Math.round(fractional * 100)}% of spacing values land on fractions. Set html { font-size: 100% } and size things with the scale instead.`,
      offGrid.slice(0, 6).map(([v, c]) => `${v}px ×${c}`)
    );
  } else if (conformity < 0.7) add("Spacing", "error", "spacing-grid", `Only ${Math.round(conformity * 100)}% of spacing values sit on the 4px grid (2px half-steps allowed under 16px).`, offGrid.map(([v, c]) => `${v}px ×${c}`));
  else if (conformity < 0.85) add("Spacing", "warn", "spacing-grid", `${Math.round(conformity * 100)}% of spacing values sit on the 4px grid; aim for 85%+.`, offGrid.map(([v, c]) => `${v}px ×${c}`));
  const radii = histogram(d.radii);
  if (radii.length > 5) add("Spacing", "warn", "radii", `${radii.length} distinct border radii; keep 2–4.`, radii.map(([r, c]) => `${r}px ×${c}`));

  // ---------- Components ----------
  const colors = histogram(d.texts.map((t) => t.color.join(",")));
  if (colors.length > 12) add("Components", "warn", "text-colors", `${colors.length} distinct text colors; consolidate into a few neutrals + accent.`);
  const shadows = histogram(d.shadows);
  if (shadows.length > 4) add("Components", "warn", "shadows", `${shadows.length} distinct box-shadows; keep 2–3 elevation levels.`);
  const clickDivs = d.interactive.filter((i) => i.clickableNonInteractive);
  if (clickDivs.length) add("Components", "error", "clickable-div", "Clickable non-interactive elements; use <button> or <a>.", clickDivs.map((i) => i.sel));

  // ---------- Visuals ----------
  const broken = d.images.filter((i) => i.broken);
  if (broken.length) add("Visuals", "error", "broken-images", "Images failed to load.", broken.map((i) => i.src));
  const distorted = d.images.filter((i) => i.naturalRatio && i.renderedRatio && i.objectFit === "fill" && Math.abs(i.naturalRatio / i.renderedRatio - 1) > 0.05);
  if (distorted.length) add("Visuals", "warn", "distorted-images", "Images stretched out of their ratio; use object-fit: cover and a fixed aspect-ratio.", distorted.map((i) => i.sel));
  const noDims = d.images.filter((i) => !i.hasDimensions);
  if (noDims.length) add("Visuals", "info", "image-dimensions", "Images without width/height attributes (layout shift).", noDims.map((i) => i.sel));

  // ---------- Content ----------
  if (d.lorem) add("Content", "error", "lorem", "Placeholder lorem ipsum text found.");
  if (d.vagueLinks) add("Content", "warn", "vague-links", `${d.vagueLinks} vague link label(s) like "click here" / "read more"; use verb + object.`);
  if (!d.title) add("Content", "warn", "title", "Missing <title>.");

  // ---------- Wrapping & clipping (checked at both widths) ----------
  const views = [["desktop", d], ["mobile", m]].filter(([, v], i, arr) => i === 0 || v !== arr[0][1]);
  const wrappedNumbers = new Map();
  const wrappedControls = new Map();
  const clipped = new Map();
  for (const [label, v] of views) {
    for (const t of v.texts || []) if (t.isNumber && t.lines > 1) wrappedNumbers.set(t.sel + t.text, `${t.sel} "${t.text}" (${label}, ${t.lines} lines)`);
    for (const i of v.interactive || [])
      if (["button", "a", "summary"].includes(i.tag) && !i.inline && i.lines > 1 && i.text.length <= 28) wrappedControls.set(i.sel + i.text, `${i.sel} "${i.text}" (${label})`);
    for (const c of v.clipped || []) clipped.set(c.sel + label, { ...c, label });
  }
  if (wrappedNumbers.size) add("Responsive", "error", "wrapped-number", "Numbers break across lines; keep amounts on one line (white-space: nowrap + tabular-nums) and give the column room.", [...wrappedNumbers.values()]);
  if (wrappedControls.size) add("Components", "warn", "wrapped-control", "Button or link labels wrap onto two lines; shorten the label, add whitespace-nowrap, or let the control shrink others.", [...wrappedControls.values()]);
  const cut = [...clipped.values()].filter((c) => !c.scrollable);
  const scroll = [...clipped.values()].filter((c) => c.scrollable);
  if (cut.length) add("Responsive", "error", "clipped-content", "Content is cut off by an overflow: hidden container and can't be reached.", cut.map((c) => `${c.sel} (${c.label}) hides "${c.examples.join('", "')}"`));
  if (scroll.length)
    add("Responsive", "warn", "hidden-scroll-content", "Content sits off-screen in a horizontal scroll area; key columns (totals, status, actions) should stay visible — stack or drop secondary columns on mobile.", scroll.map((c) => `${c.sel} (${c.label}, ${c.hiddenPx}px hidden) e.g. "${c.examples.join('", "')}"`));

  // ---------- Responsive ----------
  if (!m.hasViewportMeta) add("Responsive", "error", "viewport-meta", 'Missing <meta name="viewport">.');
  if (m.overflowX > 1) add("Responsive", "error", "overflow", `Horizontal overflow of ${m.overflowX}px on mobile.`);
  const targets = m.interactive.filter((i) => !i.inline && i.width > 0);
  const isControl = (i) => i.tag !== "a";
  const tiny = targets.filter((i) => (i.width < 24 || i.height < 24) && isControl(i));
  if (tiny.length) add("Responsive", "error", "tap-target-min", "Controls under 24px (WCAG 2.2 target size minimum).", tiny.map((i) => `${i.sel} ${i.width}×${i.height}`));
  const small = targets.filter((i) => !tiny.includes(i) && i.height < 36 && (isControl(i) || i.height < 24));
  if (small.length > 2) add("Responsive", "warn", "tap-target", "Touch targets under 36px tall on mobile (44px is comfortable; standalone text links need ≥ 24px or spacing).", small.map((i) => `${i.sel} ${i.width}×${i.height}`));
  const tinyText = m.texts.filter((t) => t.fontSize < 12 && t.chars > 3);
  if (tinyText.length) add("Responsive", "warn", "tiny-text", "Text below 12px on mobile.", tinyText.map((t) => `${t.sel} ${t.fontSize}px "${t.text}"`));
  const smallBody = m.paragraphs.filter((p) => p.fontSize < 15);
  if (smallBody.length) add("Responsive", "warn", "mobile-body-size", "Paragraph text under 15px on mobile; use 16px.", smallBody.map((p) => `${p.sel} ${p.fontSize}px`));

  // ---------- Accessibility ----------
  const contrast = [...contrastIssues(d.texts), ...contrastIssues(m.texts)];
  const uniqueContrast = [...new Map(contrast.map((c) => [c.sel + c.ratio, c])).values()];
  if (uniqueContrast.length)
    add("Accessibility", uniqueContrast.length > 3 ? "error" : "warn", "contrast", "Text below WCAG AA contrast.", uniqueContrast.map((c) => `${c.sel} "${c.text}" ${c.ratio}:1 (needs ${c.required}:1)`));
  const noAlt = d.images.filter((i) => !i.hasAlt);
  if (noAlt.length) add("Accessibility", "error", "img-alt", "Images without an alt attribute.", noAlt.map((i) => i.src));
  const unlabeled = d.fields.filter((f) => !f.labelled);
  if (unlabeled.length) add("Accessibility", "error", "form-labels", "Form fields without a label.", unlabeled.map((f) => f.sel));
  const nameless = d.interactive.filter((i) => !i.hasName);
  if (nameless.length) add("Accessibility", "error", "accessible-name", "Interactive elements without an accessible name (icon buttons need aria-label).", nameless.map((i) => i.sel));
  if (!d.lang) add("Accessibility", "warn", "lang", "Missing lang attribute on <html>.");
  const levels = d.headings.map((h) => h.level);
  const skips = levels.filter((l, i) => i > 0 && l - levels[i - 1] > 1);
  if (skips.length) add("Accessibility", "warn", "heading-order", "Heading levels skip (e.g. h2 → h4).");

  return findings;
}

/** Score 1–5 per criterion from findings. Criteria that can't be fully measured are flagged. */
function score(findings) {
  const scores = {};
  for (const c of CRITERIA) {
    const penalty = findings.filter((f) => f.criterion === c).reduce((s, f) => s + PENALTY[f.severity], 0);
    scores[c] = Math.max(1, Math.round((5 - penalty) * 2) / 2);
  }
  const total = Object.values(scores).reduce((a, b) => a + b, 0);
  return { scores, total, max: CRITERIA.length * 5 };
}

/** Design-token summary useful for both audits and reference extraction. */
function summarizeTokens(data) {
  const byChars = new Map();
  for (const t of data.texts) byChars.set(t.fontFamily, (byChars.get(t.fontFamily) || 0) + t.chars);
  const totalChars = [...byChars.values()].reduce((a, b) => a + b, 0) || 1;
  const fonts = [...byChars.entries()].sort((a, b) => b[1] - a[1]).map(([f, c]) => ({ family: f, share: Math.round((c / totalChars) * 100) }));
  const typeScale = histogram(data.texts.map((t) => t.fontSize), Math.round).map(([s]) => s).sort((a, b) => b - a);
  const weights = histogram(data.texts.map((t) => t.fontWeight)).map(([w]) => w).sort((a, b) => a - b);
  const headings = data.headings.slice(0, 6).map((h) => ({
    level: h.level,
    fontSize: h.fontSize,
    letterSpacingEm: h.fontSize ? Math.round((h.letterSpacing / h.fontSize) * 1000) / 1000 : 0,
    lineHeight: h.lineHeight && h.fontSize ? Math.round((h.lineHeight / h.fontSize) * 100) / 100 : null,
    text: h.text,
  }));
  return {
    fonts,
    typeScale,
    weights,
    headings,
    spacing: histogram(data.spacing, Math.round).slice(0, 12).map(([v, c]) => ({ px: v, count: c })),
    gridConformity: Math.round(gridConformity(data.spacing) * 100),
    radii: histogram(data.radii).slice(0, 6).map(([v, c]) => ({ px: v, count: c })),
    shadows: histogram(data.shadows).slice(0, 4).map(([v, c]) => ({ value: v, count: c })),
  };
}

// ---- lib/probe.mjs ----
// In-page data collection. `collectPageData` is serialized and run inside the browser
// via page.evaluate, so it must stay self-contained (no imports, no outer variables).
// It only gathers raw measurements; all judgement happens in analyze.mjs (pure, testable).

function collectPageData() {
  const MAX = 4000;

  // Normalize any CSS color (rgb, hsl, oklch, color(), named…) to [r,g,b,a] through a canvas.
  const canvas = document.createElement("canvas");
  canvas.width = canvas.height = 1;
  const ctx = canvas.getContext("2d", { willReadFrequently: true });
  const cache = new Map();
  const rgba = (value) => {
    if (!value || value === "transparent") return [0, 0, 0, 0];
    if (cache.has(value)) return cache.get(value);
    ctx.clearRect(0, 0, 1, 1);
    ctx.fillStyle = "rgba(0,0,0,0)";
    ctx.fillStyle = value;
    ctx.fillRect(0, 0, 1, 1);
    const d = ctx.getImageData(0, 0, 1, 1).data;
    const out = [d[0], d[1], d[2], Math.round((d[3] / 255) * 1000) / 1000];
    cache.set(value, out);
    return out;
  };

  const selector = (el) => {
    if (el.id) return `${el.tagName.toLowerCase()}#${el.id}`;
    const cls = [...el.classList].filter((c) => !c.includes(":") && !c.includes("[")).slice(0, 2);
    const parent = el.parentElement ? el.parentElement.tagName.toLowerCase() + " > " : "";
    return parent + el.tagName.toLowerCase() + (cls.length ? "." + cls.join(".") : "");
  };

  const visible = (el) => {
    const r = el.getBoundingClientRect();
    if (r.width < 1 || r.height < 1) return false;
    const s = getComputedStyle(el);
    if (s.visibility === "hidden" || s.display === "none") return false;
    let n = el;
    while (n && n !== document.documentElement) {
      if (getComputedStyle(n).opacity === "0") return false;
      if (n.hasAttribute && (n.hasAttribute("hidden") || n.hasAttribute("inert") || n.getAttribute("aria-hidden") === "true")) return false;
      n = n.parentElement;
    }
    return true;
  };

  const srOnly = (el) => {
    const r = el.getBoundingClientRect();
    return r.width <= 1 && r.height <= 1;
  };

  // Background stack from the element up to the first opaque layer.
  const backgroundStack = (el) => {
    const layers = [];
    let hasImage = false;
    let n = el;
    while (n && n.nodeType === 1) {
      const s = getComputedStyle(n);
      if (s.backgroundImage && s.backgroundImage !== "none") hasImage = true;
      const c = rgba(s.backgroundColor);
      if (c[3] > 0) {
        layers.push(c);
        if (c[3] >= 1) break;
      }
      n = n.parentElement;
    }
    return { layers, hasImage };
  };

  const px = (v) => (v === "normal" ? null : parseFloat(v));

  // Number of rendered lines for an element's content (1 = no wrap).
  // Only text boxes count (icons and mixed font sizes on one baseline don't), and boxes that
  // overlap vertically belong to the same line.
  const lineCount = (el) => {
    const rects = [];
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    const range = document.createRange();
    for (let n = walker.nextNode(); n; n = walker.nextNode()) {
      if (!n.textContent.trim()) continue;
      range.selectNodeContents(n);
      for (const q of range.getClientRects()) if (q.width > 0 && q.height > 0) rects.push(q);
    }
    rects.sort((a, b) => a.top - b.top);
    let lines = 0;
    let bottom = -Infinity;
    for (const q of rects) {
      if (q.top >= bottom - 2) {
        lines++;
        bottom = q.bottom;
      } else bottom = Math.max(bottom, q.bottom);
    }
    return Math.max(1, lines);
  };
  const NUMBER = /^[\s+\-−–]*(?:[€$£]\s?)?[\d][\d\s.,\u00a0\u202f]*\s?(?:€|\$|£|%|k|K|M|x|×)?$/;
  const all = [...document.body.querySelectorAll("*")].slice(0, MAX);

  const texts = [];
  const spacing = [];
  const radii = [];
  const shadows = [];
  const clipped = [];
  for (const el of all) {
    if (["SCRIPT", "STYLE", "NOSCRIPT", "TEMPLATE"].includes(el.tagName.toUpperCase()) || el.closest("svg")) continue;
    if (!visible(el)) continue;
    const s = getComputedStyle(el);

    const ownText = [...el.childNodes]
      .filter((n) => n.nodeType === 3)
      .map((n) => n.textContent)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
    const disabled = el.closest(":disabled, [aria-disabled=true]");
    if (ownText && !srOnly(el) && !disabled) {
      const r = el.getBoundingClientRect();
      const bg = backgroundStack(el);
      texts.push({
        sel: selector(el),
        tag: el.tagName.toLowerCase(),
        text: ownText.slice(0, 60),
        chars: ownText.length,
        fontSize: px(s.fontSize),
        fontWeight: Number(s.fontWeight) || 400,
        lineHeight: px(s.lineHeight),
        letterSpacing: px(s.letterSpacing) ?? 0,
        fontFamily: s.fontFamily.split(",")[0].replace(/["']/g, "").trim(),
        color: rgba(s.color),
        opacity: Number(s.opacity),
        bgLayers: bg.layers,
        bgImage: bg.hasImage,
        width: Math.round(r.width),
        lines: ownText.length <= 40 ? lineCount(el) : null,
        isNumber: NUMBER.test(ownText),
      });
    }

    // Content pushed out of a scroll/clip container: only counts when real text is hidden.
    if (["auto", "scroll", "hidden", "clip"].includes(s.overflowX) && el.clientWidth > 0 && el.scrollWidth - el.clientWidth > 4) {
      const box = el.getBoundingClientRect();
      const hiddenText = [...el.querySelectorAll("*")].filter((c) => {
        if (!c.childNodes.length || ![...c.childNodes].some((n) => n.nodeType === 3 && n.textContent.trim())) return false;
        const q = c.getBoundingClientRect();
        return q.width > 0 && (q.left >= box.right - 1 || q.right > box.right + 8) && visible(c);
      });
      if (hiddenText.length)
        clipped.push({
          sel: selector(el),
          hiddenPx: el.scrollWidth - el.clientWidth,
          scrollable: s.overflowX === "auto" || s.overflowX === "scroll",
          examples: hiddenText.slice(0, 3).map((c) => c.textContent.replace(/\s+/g, " ").trim().slice(0, 30)),
          hiddenCount: hiddenText.length,
        });
    }

    for (const prop of ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft", "marginTop", "marginBottom", "rowGap", "columnGap"]) {
      const v = parseFloat(s[prop]);
      if (v > 0 && Number.isFinite(v)) spacing.push(Math.round(v * 100) / 100);
    }
    const rad = parseFloat(s.borderTopLeftRadius);
    if (rad > 0 && rad < 999) radii.push(Math.round(rad * 10) / 10);
    if (s.boxShadow && s.boxShadow !== "none") shadows.push(s.boxShadow);
  }

  const interactiveSel = "a[href], button, input:not([type=hidden]), select, textarea, summary, [role=button], [role=link], [role=tab], [role=radio], [onclick]";
  const interactive = [...document.querySelectorAll(interactiveSel)]
    .filter((el) => visible(el) || (el.tagName === "INPUT" && el.labels && el.labels.length))
    .map((el) => {
      // Visually hidden radio/checkbox: measure its visible label instead
      let box = el;
      if (el.tagName === "INPUT" && srOnly(el) && el.labels && el.labels[0]) box = el.labels[0];
      const r = box.getBoundingClientRect();
      const tag = el.tagName.toLowerCase();
      const parentText = el.parentElement ? el.parentElement.textContent.trim().length : 0;
      const inline = tag === "a" && getComputedStyle(el).display === "inline" && parentText > el.textContent.trim().length + 20;
      const name = (
        el.getAttribute("aria-label") ||
        el.getAttribute("aria-labelledby") ||
        el.getAttribute("title") ||
        el.textContent ||
        [...el.querySelectorAll("img[alt]")].map((i) => i.alt).join(" ") ||
        (el.labels && el.labels.length ? "label" : "") ||
        el.getAttribute("placeholder") ||
        el.value ||
        ""
      ).trim();
      const nativeInteractive = ["a", "button", "input", "select", "textarea", "summary"].includes(tag) || el.getAttribute("role");
      return {
        sel: selector(el),
        tag,
        width: Math.round(r.width),
        height: Math.round(r.height),
        inline,
        hasName: name.length > 0,
        clickableNonInteractive: el.hasAttribute("onclick") && !nativeInteractive,
        text: (el.textContent || "").replace(/\s+/g, " ").trim().slice(0, 40),
        lines: (el.textContent || "").trim().length && (el.textContent || "").trim().length <= 40 ? lineCount(el) : 1,
      };
    });

  const images = [...document.images].filter(visible).map((img) => {
    const r = img.getBoundingClientRect();
    const s = getComputedStyle(img);
    return {
      sel: selector(img),
      src: (img.currentSrc || img.src || "").slice(0, 120),
      hasAlt: img.hasAttribute("alt"),
      hasDimensions: img.hasAttribute("width") && img.hasAttribute("height"),
      broken: img.complete && img.naturalWidth === 0,
      naturalRatio: img.naturalWidth && img.naturalHeight ? img.naturalWidth / img.naturalHeight : null,
      renderedRatio: r.height ? r.width / r.height : null,
      objectFit: s.objectFit,
    };
  });

  const fields = [...document.querySelectorAll("input:not([type=hidden]):not([type=submit]):not([type=button]), select, textarea")].map((el) => ({
    sel: selector(el),
    labelled: Boolean((el.labels && el.labels.length) || el.getAttribute("aria-label") || el.getAttribute("aria-labelledby") || el.getAttribute("title")),
  }));

  const headings = [...document.querySelectorAll("h1, h2, h3, h4, h5, h6")].filter(visible).map((h) => {
    const s = getComputedStyle(h);
    return {
      level: Number(h.tagName[1]),
      text: h.textContent.replace(/\s+/g, " ").trim().slice(0, 60),
      fontSize: parseFloat(s.fontSize),
      letterSpacing: px(s.letterSpacing) ?? 0,
      lineHeight: px(s.lineHeight),
    };
  });

  const paragraphs = [...document.querySelectorAll("p, li, blockquote, dd")]
    .filter((el) => visible(el) && el.textContent.trim().length > 90 && !el.querySelector("p, div, ul, ol, table"))
    .map((el) => {
      const s = getComputedStyle(el);
      const fs = parseFloat(s.fontSize);
      return {
        sel: selector(el),
        fontSize: fs,
        lineHeight: px(s.lineHeight),
        measure: Math.round(el.getBoundingClientRect().width / (fs * 0.5)),
      };
    });

  const bodyText = document.body.innerText || "";
  return {
    url: location.href,
    viewport: { width: window.innerWidth, height: window.innerHeight },
    title: document.title,
    lang: document.documentElement.getAttribute("lang") || "",
    hasViewportMeta: Boolean(document.querySelector('meta[name="viewport"]')),
    hasDescription: Boolean(document.querySelector('meta[name="description"]')),
    overflowX: Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth),
    pageHeight: document.documentElement.scrollHeight,
    lorem: /lorem ipsum|dolor sit amet/i.test(bodyText),
    vagueLinks: interactive.filter((i) => /^(click here|here|read more|learn more|more|cliquez ici|en savoir plus)$/i.test(i.text)).length,
    texts,
    interactive,
    images,
    fields,
    headings,
    paragraphs,
    spacing,
    radii,
    shadows,
    clipped,
    rootFontSize: parseFloat(getComputedStyle(document.documentElement).fontSize),
  };
}

// ---- lib/report.mjs ----
// Human-readable audit report (pure — also bundled into audit.browser.js).

const ICON = { error: "✗", warn: "!", info: "·" };
const SHORT = { Hierarchy: "Hierarchy", Typography: "Typography", Spacing: "Spacing", Components: "Components", Visuals: "Visuals*", Content: "Content*", Responsive: "Responsive", Accessibility: "A11y" };

/** Format an audit result ({ target, scores, total, max, findings, tokens, note? }) like references/audit.md. */
function formatReport(result) {
  const lines = [];
  lines.push(`Automated audit — ${result.target}`);
  if (result.note) lines.push(result.note);
  lines.push("Audit: " + CRITERIA.map((c) => `${SHORT[c]} ${result.scores[c]}`).join(" · ") + ` → ${result.total}/${result.max}`);
  lines.push("(* partly measurable — confirm with a visual review of the screenshots)");
  lines.push("");
  const order = { error: 0, warn: 1, info: 2 };
  const sorted = [...result.findings].sort((a, b) => order[a.severity] - order[b.severity]);
  if (!sorted.length) lines.push("No automated findings.");
  for (const f of sorted) {
    lines.push(`${ICON[f.severity]} [${f.criterion}] ${f.message}${f.count > f.items.length ? ` (${f.count} total)` : ""}`);
    for (const item of f.items) lines.push(`    ${item}`);
  }
  const t = result.tokens;
  if (t) {
    lines.push("");
    lines.push("Measured tokens");
    lines.push(`  Fonts: ${t.fonts.map((f) => `${f.family} ${f.share}%`).join(", ")}`);
    lines.push(`  Type scale (px): ${t.typeScale.join(" / ")}`);
    lines.push(`  Spacing on 4px grid: ${t.gridConformity}% · most used: ${t.spacing.slice(0, 8).map((s) => s.px).join(", ")}`);
    lines.push(`  Radii (px): ${t.radii.map((r) => r.px).join(", ") || "none"}`);
  }
  return lines.join("\n");
}

const data = collectPageData();
const findings = analyze(data, data);
const result = {
  target: location.href,
  note: "Viewport: " + innerWidth + "px (single-viewport audit — rerun at 390px for mobile checks)",
  ...score(findings),
  findings,
  tokens: summarizeTokens(data),
};
const report = formatReport(result);
console.log(report);
return { report, result };
})();
