// ui-ux-glowup — in-browser audit. GENERATED by build-browser-audit.mjs, do not edit.
// Paste into the DevTools console of the page to audit (works on logged-in pages).
// Audits the current viewport only: run it once at desktop width and once with the
// device toolbar at 390px to get the mobile checks.
// Returns { report, result } and prints the report.
(() => {
// ---- lib/color.mjs ----
// Pure color utilities (no browser needed). Colors are [r, g, b, a] with r,g,b in 0-255 and a in 0-1.

/** Composite a (possibly translucent) foreground over an opaque background. */
function composite(fg, bg) {
  const a = fg[3] ?? 1;
  return [
    Math.round(fg[0] * a + bg[0] * (1 - a)),
    Math.round(fg[1] * a + bg[1] * (1 - a)),
    Math.round(fg[2] * a + bg[2] * (1 - a)),
    1,
  ];
}

/**
 * Resolve the effective opaque background from a stack of layers,
 * ordered from the element itself up to the root. Falls back to white.
 */
function flattenBackground(layers, fallback = [255, 255, 255, 1]) {
  let result = fallback;
  for (let i = layers.length - 1; i >= 0; i--) {
    const layer = layers[i];
    if (!layer || layer[3] === 0) continue;
    result = composite(layer, result);
  }
  return result;
}

/** WCAG 2.x relative luminance. */
function luminance([r, g, b]) {
  const lin = (c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

/** WCAG 2.x contrast ratio between two opaque colors, rounded to 2 decimals. */
function contrastRatio(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la > lb ? [la, lb] : [lb, la];
  return Math.round(((hi + 0.05) / (lo + 0.05)) * 100) / 100;
}

/** WCAG large text: >= 24px, or >= 18.66px (14pt) and bold (>= 700). */
function isLargeText(fontSizePx, fontWeight) {
  return fontSizePx >= 24 || (fontSizePx >= 18.66 && Number(fontWeight) >= 700);
}

/** Minimum AA ratio for a given text size / weight. */
function requiredRatio(fontSizePx, fontWeight) {
  return isLargeText(fontSizePx, fontWeight) ? 3 : 4.5;
}

function toHex([r, g, b]) {
  return "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
}

// ---- lib/analyze.mjs ----
// Pure analysis of data collected by probe.mjs. No browser needed — fully unit-testable.

const CRITERIA = ["Hierarchy", "Typography", "Spacing", "Components", "Visuals", "Content", "Responsive", "Accessibility", "SEO"];

const PENALTY = { error: 1, warn: 0.5, info: 0 };

/** Group numbers and return [value, count] sorted by count desc. */
function histogram(values, round = (v) => v) {
  const map = new Map();
  for (const v of values) {
    const k = round(v);
    map.set(k, (map.get(k) || 0) + 1);
  }
  return [...map.entries()].sort((a, b) => b[1] - a[1]);
}

/** A spacing value is on-grid if it's a multiple of 4px, or of 2px below 16px (half steps like 6px, 10px). */
function onGrid(v) {
  const step = v < 16 ? 2 : 4;
  return Math.abs(v / step - Math.round(v / step)) < 0.01;
}

/** Share of spacing values (>= 2px) that sit on the grid. */
function gridConformity(values) {
  const relevant = values.filter((v) => v >= 2);
  if (!relevant.length) return 1;
  return relevant.filter(onGrid).length / relevant.length;
}

/** Most common paragraph font size, falling back to the most common non-heading text size. */
function bodyFontSize(data) {
  const para = histogram(data.paragraphs.map((p) => p.fontSize), Math.round);
  if (para.length) return para[0][0];
  const texts = histogram(data.texts.filter((t) => !/^h[1-6]$/.test(t.tag)).map((t) => t.fontSize), Math.round);
  return texts.length ? texts[0][0] : 16;
}

/** Contrast failures for collected text nodes. Skips text over background images (unknowable). */
function contrastIssues(texts) {
  const seen = new Set();
  const out = [];
  for (const t of texts) {
    if (t.bgImage || !t.fontSize) continue;
    const bg = flattenBackground(t.bgLayers);
    const fg = composite(t.color, bg);
    const ratio = contrastRatio(fg, bg);
    const need = requiredRatio(t.fontSize, t.fontWeight);
    const key = t.sel + "|" + ratio;
    if (ratio < need && !seen.has(key)) {
      seen.add(key);
      out.push({ sel: t.sel, text: t.text, ratio, required: need });
    }
  }
  return out.sort((a, b) => a.ratio - b.ratio);
}

/** Produce findings from desktop + mobile page data. */
function analyze(desktop, mobile) {
  const findings = [];
  const add = (criterion, severity, rule, message, items = []) =>
    findings.push({ criterion, severity, rule, message, items: items.slice(0, 8), count: items.length || undefined });

  const d = desktop;
  const m = mobile || desktop;

  // ---------- Hierarchy ----------
  const h1s = d.headings.filter((h) => h.level === 1);
  if (h1s.length === 0) add("Hierarchy", "error", "h1-missing", "No <h1> on the page.");
  if (h1s.length > 1) add("Hierarchy", "warn", "h1-multiple", `${h1s.length} <h1> elements; use one per page.`, h1s.map((h) => h.text));
  const bodySize = bodyFontSize(d);
  if (h1s[0] && h1s[0].fontSize / bodySize < 1.8)
    add("Hierarchy", "warn", "h1-weak", `<h1> is only ${(h1s[0].fontSize / bodySize).toFixed(1)}× body size (${h1s[0].fontSize}px vs ${bodySize}px). Aim for 2.5× or more on landing pages.`);

  // ---------- Typography ----------
  const families = histogram(d.texts.map((t) => t.fontFamily)).filter(([f]) => !/mono|courier|consolas|menlo/i.test(f));
  if (families.length > 2) add("Typography", "warn", "font-families", `${families.length} font families in use; keep to 2.`, families.map(([f, c]) => `${f} (${c})`));
  const sizes = histogram(d.texts.map((t) => t.fontSize), (v) => Math.round(v));
  if (sizes.length > 10) add("Typography", "warn", "type-scale", `${sizes.length} distinct font sizes; use a tighter type scale (≈ 6–9 steps).`, sizes.map(([s, c]) => `${s}px ×${c}`));
  const tightBody = d.paragraphs.filter((p) => p.fontSize < 24 && p.lineHeight && p.lineHeight / p.fontSize < 1.4);
  if (tightBody.length) add("Typography", "warn", "line-height", "Paragraph line-height below 1.4.", tightBody.map((p) => `${p.sel} (${(p.lineHeight / p.fontSize).toFixed(2)})`));
  const wide = d.paragraphs.filter((p) => p.measure > 85);
  if (wide.length) add("Typography", "warn", "measure", "Lines longer than ~85 characters; cap paragraphs around 65ch.", wide.map((p) => `${p.sel} (~${p.measure}ch)`));
  const looseHeadings = d.headings.filter((h) => h.fontSize >= 32 && h.letterSpacing >= 0);
  if (looseHeadings.length)
    add("Typography", "info", "heading-tracking", "Large headings with default tracking; -0.02em to -0.04em usually reads more refined.", looseHeadings.map((h) => `${h.text} (${h.fontSize}px)`));

  // ---------- Spacing ----------
  const conformity = gridConformity(d.spacing);
  const offGrid = histogram(d.spacing.filter((v) => v >= 2 && !onGrid(v)));
  const root = d.rootFontSize || 16;
  if (root !== 16) {
    const fractional = d.spacing.filter((v) => !Number.isInteger(v)).length / (d.spacing.length || 1);
    add(
      "Spacing",
      fractional > 0.3 ? "error" : "warn",
      "root-font-size",
      `Root cause: <html> font-size is ${root}px instead of 16px, so every rem value (Tailwind spacing, text sizes, radii) is scaled by ${(root / 16).toFixed(4)} and ${Math.round(fractional * 100)}% of spacing values land on fractions. Set html { font-size: 100% } and size things with the scale instead.`,
      offGrid.slice(0, 6).map(([v, c]) => `${v}px ×${c}`)
    );
  } else if (conformity < 0.7) add("Spacing", "error", "spacing-grid", `Only ${Math.round(conformity * 100)}% of spacing values sit on the 4px grid (2px half-steps allowed under 16px).`, offGrid.map(([v, c]) => `${v}px ×${c}`));
  else if (conformity < 0.85) add("Spacing", "warn", "spacing-grid", `${Math.round(conformity * 100)}% of spacing values sit on the 4px grid; aim for 85%+.`, offGrid.map(([v, c]) => `${v}px ×${c}`));
  const radii = histogram(d.radii);
  if (radii.length > 5) add("Spacing", "warn", "radii", `${radii.length} distinct border radii; keep 2–4.`, radii.map(([r, c]) => `${r}px ×${c}`));

  // ---------- Components ----------
  const colors = histogram(d.texts.map((t) => t.color.join(",")));
  if (colors.length > 12) add("Components", "warn", "text-colors", `${colors.length} distinct text colors; consolidate into a few neutrals + accent.`);
  const shadows = histogram(d.shadows);
  if (shadows.length > 4) add("Components", "warn", "shadows", `${shadows.length} distinct box-shadows; keep 2–3 elevation levels.`);
  const clickDivs = d.interactive.filter((i) => i.clickableNonInteractive);
  if (clickDivs.length) add("Components", "error", "clickable-div", "Clickable non-interactive elements; use <button> or <a>.", clickDivs.map((i) => i.sel));

  // ---------- Visuals ----------
  const broken = d.images.filter((i) => i.broken);
  if (broken.length) add("Visuals", "error", "broken-images", "Images failed to load.", broken.map((i) => i.src));
  const distorted = d.images.filter((i) => i.naturalRatio && i.renderedRatio && i.objectFit === "fill" && Math.abs(i.naturalRatio / i.renderedRatio - 1) > 0.05);
  if (distorted.length) add("Visuals", "warn", "distorted-images", "Images stretched out of their ratio; use object-fit: cover and a fixed aspect-ratio.", distorted.map((i) => i.sel));
  const noDims = d.images.filter((i) => !i.hasDimensions);
  if (noDims.length) add("Visuals", "info", "image-dimensions", "Images without width/height attributes (layout shift).", noDims.map((i) => i.sel));

  // ---------- Content ----------
  if (d.lorem) add("Content", "error", "lorem", "Placeholder lorem ipsum text found.");
  if (d.vagueLinks) add("Content", "warn", "vague-links", `${d.vagueLinks} vague link label(s) like "click here" / "read more"; use verb + object.`);

  // ---------- Wrapping & clipping (checked at both widths) ----------
  const views = [["desktop", d], ["mobile", m]].filter(([, v], i, arr) => i === 0 || v !== arr[0][1]);
  const wrappedNumbers = new Map();
  const wrappedControls = new Map();
  const clipped = new Map();
  for (const [label, v] of views) {
    for (const t of v.texts || []) if (t.isNumber && t.lines > 1) wrappedNumbers.set(t.sel + t.text, `${t.sel} "${t.text}" (${label}, ${t.lines} lines)`);
    for (const i of v.interactive || [])
      if (["button", "a", "summary"].includes(i.tag) && !i.inline && i.lines > 1 && i.text.length <= 28) wrappedControls.set(i.sel + i.text, `${i.sel} "${i.text}" (${label})`);
    for (const c of v.clipped || []) clipped.set(c.sel + label, { ...c, label });
  }
  if (wrappedNumbers.size) add("Responsive", "error", "wrapped-number", "Numbers break across lines; keep amounts on one line (white-space: nowrap + tabular-nums) and give the column room.", [...wrappedNumbers.values()]);
  if (wrappedControls.size) add("Components", "warn", "wrapped-control", "Button or link labels wrap onto two lines; shorten the label, add whitespace-nowrap, or let the control shrink others.", [...wrappedControls.values()]);
  const cut = [...clipped.values()].filter((c) => !c.scrollable);
  const scroll = [...clipped.values()].filter((c) => c.scrollable);
  if (cut.length) add("Responsive", "error", "clipped-content", "Content is cut off by an overflow: hidden container and can't be reached.", cut.map((c) => `${c.sel} (${c.label}) hides "${c.examples.join('", "')}"`));
  if (scroll.length)
    add("Responsive", "warn", "hidden-scroll-content", "Content sits off-screen in a horizontal scroll area; key columns (totals, status, actions) should stay visible — stack or drop secondary columns on mobile.", scroll.map((c) => `${c.sel} (${c.label}, ${c.hiddenPx}px hidden) e.g. "${c.examples.join('", "')}"`));

  // ---------- Mobile interaction (clicks, forms, sliders) ----------
  const mi = m.mobile;
  if (mi) {
    if (mi.zoomBlocked) add("Accessibility", "error", "zoom-blocked", "The viewport meta blocks pinch-zoom (user-scalable=no / maximum-scale=1); remove it — users with low vision need to zoom.");
    if (mi.smallInputs?.length) add("Responsive", "warn", "input-zoom", "Form fields under 16px make iOS Safari zoom in on focus; use font-size: 16px on inputs.", mi.smallInputs.map((f) => `${f.sel} ${f.fontSize}px`));
    if (mi.crowded?.length) add("Responsive", "warn", "tap-crowded", "Touch targets under 36px packed less than 8px apart — easy to hit the wrong one on a phone; add spacing or enlarge them (44px is comfortable).", mi.crowded.map((c) => `${c.sel}${c.text ? ` "${c.text}"` : ""} ↔ ${c.other} (${c.gap}px)`));
    const big = (mi.overlays || []).filter((o) => o.coverage >= 25);
    if (big.length) add("Responsive", big.some((o) => o.coverage >= 40) ? "error" : "warn", "fixed-overlay", "Fixed/sticky elements cover a large part of the mobile screen; shrink them, make them dismissible, or only stick a slim bar.", big.map((o) => `${o.sel} covers ${o.coverage}% (${o.position})`));
    if (mi.touchBlockers?.length) add("Responsive", "warn", "touch-blocked", "Large areas with touch-action: none block scrolling on phones.", mi.touchBlockers);
  }
  const cars = [...(d.mobile?.carousels || []), ...(mi?.carousels || [])].filter((c, i, arr) => arr.findIndex((x) => x.sel === c.sel) === i);
  const noSnap = cars.filter((c) => c.kind === "native" && !c.snap);
  if (noSnap.length) add("Components", "warn", "carousel-snap", "Swipe areas without scroll-snap stop between slides; add scroll-snap-type: x mandatory on the track and scroll-snap-align on items.", noSnap.map((c) => `${c.sel} (${c.items} items)`));
  const unnamed = cars.filter((c) => c.controls > c.namedControls);
  if (unnamed.length) add("Accessibility", "warn", "carousel-controls", "Slider arrows without an accessible name; add aria-label=\"Previous slide\" / \"Next slide\".", unnamed.map((c) => c.sel));
  const tinyCtl = cars.filter((c) => c.smallControls > 0);
  if (tinyCtl.length) add("Responsive", "warn", "carousel-small-controls", "Slider controls under 32px are hard to tap; use at least 40–44px.", tinyCtl.map((c) => `${c.sel} (${c.smallControls} small)`));
  const noCue = cars.filter((c) => c.kind === "native" && !c.indicators && c.controls === 0);
  if (noCue.length) add("Components", "info", "carousel-affordance", "Horizontal lists with no arrows or dots: let the next item peek (~15%) so people know they can swipe.", noCue.map((c) => c.sel));

  // ---------- Space between blocks ----------
  for (const [label, v, min] of [["desktop", d, 24], ["mobile", m, 20]]) {
    const gaps = (v.sectionGaps || []).filter((g) => g.gap > -1);
    const tight = gaps.filter((g) => g.gap < min);
    if (tight.length) add("Spacing", "warn", `section-gap-${label}`, `Blocks almost touching on ${label} (< ${min}px of air between their content); give sections consistent vertical padding.`, tight.map((g) => `${g.between[0]} → ${g.between[1]}: ${g.gap}px`));
    const roomy = gaps.filter((g) => g.gap >= 16).map((g) => g.gap);
    if (label === "desktop" && roomy.length >= 3 && Math.max(...roomy) / Math.min(...roomy) > 3)
      add("Spacing", "warn", "section-rhythm", `Uneven rhythm between sections (${Math.min(...roomy)}px to ${Math.max(...roomy)}px); use one or two section spacings (e.g. 96/128px desktop, 64px mobile).`, gaps.map((g) => `${g.between[1]}: ${g.gap}px`));
  }

  // ---------- SEO ----------
  const seo = d.seo;
  if (seo) {
    if (!seo.title) add("SEO", "error", "seo-title", "Missing <title>.");
    else if (seo.title.length < 25 || seo.title.length > 65) add("SEO", "warn", "seo-title-length", `Title is ${seo.title.length} characters; aim for 30–60, main topic first, brand last.`, [seo.title]);
    if (!seo.description) add("SEO", "error", "seo-description", "Missing meta description (the snippet under the result in Google).");
    else if (seo.description.length < 70 || seo.description.length > 165) add("SEO", "warn", "seo-description-length", `Meta description is ${seo.description.length} characters; aim for 120–160.`, [seo.description]);
    if (/noindex/i.test(seo.robots)) add("SEO", "error", "seo-noindex", "Page is set to noindex — it won't appear in search results. Intended?");
    if (!seo.ogTitle || !seo.ogImage) add("SEO", "warn", "seo-open-graph", "Missing Open Graph tags (og:title, og:description, og:image): links shared on social apps and messengers look empty.");
    if (!seo.favicon) add("SEO", "warn", "seo-favicon", "No favicon — the tab and search result show a blank icon. Use scripts/make-favicon.mjs.");
    if (!seo.canonical) add("SEO", "info", "seo-canonical", "No canonical URL; add <link rel=\"canonical\"> on indexable pages.");
    if (!seo.jsonLd) add("SEO", "info", "seo-structured-data", "No structured data (JSON-LD): LocalBusiness, Product, Organization or FAQ markup can earn rich results.");
    if (seo.words && seo.words < 120 && d.headings.some((h) => h.level === 1)) add("SEO", "info", "seo-thin", `Only ~${seo.words} words of content; pages that should rank usually need more substance (not filler).`);
  }
  const imgs = d.images || [];
  const legacy = imgs.filter((i) => ["png", "jpg", "jpeg", "gif"].includes(i.format) && i.naturalWidth > 300);
  if (legacy.length >= 2) add("SEO", "warn", "image-format", "Photos served as JPG/PNG; WebP or AVIF are 25–50% lighter and speed up the page (Core Web Vitals).", legacy.map((i) => `${i.src} (${i.format})`));
  const heavy = imgs.filter((i) => i.naturalWidth > 1000 && i.renderedWidth && i.naturalWidth > i.renderedWidth * 2.5);
  if (heavy.length) add("SEO", "warn", "image-oversized", "Images much larger than their displayed size; resize or use srcset.", heavy.map((i) => `${i.src} ${i.naturalWidth}px shown at ${i.renderedWidth}px`));
  const eager = imgs.filter((i) => i.belowFold && !i.lazy);
  if (eager.length >= 2) add("SEO", "info", "image-lazy", "Below-the-fold images without loading=\"lazy\".", eager.map((i) => i.src));

  // ---------- Readability ----------
  const rd = d.readability || [];
  const longPara = rd.filter((p) => p.words > 90);
  if (longPara.length) add("Content", "warn", "long-paragraphs", "Paragraphs over ~90 words are skipped on screens; split them (one idea each, 2–4 sentences).", longPara.map((p) => `${p.sel} ${p.words} words "${p.text}…"`));
  const longSent = rd.filter((p) => p.avgSentence > 28 && p.words > 30);
  if (longSent.length) add("Content", "warn", "long-sentences", "Sentences average over 28 words; shorter sentences read faster (15–20 words).", longSent.map((p) => `${p.sel} ~${p.avgSentence} words/sentence`));
  const justified = rd.filter((p) => p.justified);
  if (justified.length) add("Typography", "warn", "justified-text", "Justified text creates uneven gaps (rivers) on screens, worst on mobile; align left.", justified.map((p) => p.sel));
  const caps = rd.filter((p) => p.uppercase);
  if (caps.length) add("Typography", "warn", "uppercase-text", "Long passages in uppercase are hard to read; keep caps for short labels.", caps.map((p) => p.sel));
  const smallBodyDesk = d.paragraphs.filter((p) => p.fontSize < 15);
  if (smallBodyDesk.length > 1) add("Typography", "warn", "body-size", "Body paragraphs under 15px on desktop; 16–18px reads comfortably.", smallBodyDesk.map((p) => `${p.sel} ${p.fontSize}px`));

  // ---------- "AI look" ----------
  const ai = d.aiLook;
  if (ai) {
    if (ai.gradients.length) add("Visuals", "warn", "ai-gradient", "Large purple→blue/pink gradients — the most recognizable \"AI template\" signature. Use the brand color flat, or a subtle same-hue gradient.", ai.gradients);
    if (ai.glass > 3) add("Visuals", "warn", "ai-glass", `${ai.glass} glassmorphism (backdrop blur) surfaces outside the header; keep blur for overlays and sticky bars.`);
    if (ai.radiusElements > 6 && ai.bigRadius / ai.radiusElements > 0.5) add("Visuals", "warn", "ai-radius", "Most surfaces use very large radii (≥ 24px); use 8–12px for cards, reserve large radii for a few hero elements.", ai.bigRadiusSample);
    if (ai.identicalCards.length) add("Visuals", "warn", "ai-identical-cards", "Row of 3–4 identical icon + title + text cards — the default AI layout. Vary sizes (bento), use real visuals, or a numbered list.", ai.identicalCards);
    if (ai.emoji.length) add("Content", "warn", "ai-emoji", "Emojis in headings or buttons read as generated; use proper icons or none.", ai.emoji);
    if (ai.cliches.length) add("Content", "warn", "ai-cliche", "Generic marketing phrases (\"Transform your…\", \"Unlock…\", \"seamless\", \"innovative solutions\"); say what the product concretely does.", ai.cliches);
    if (ai.heroPills?.length) add("Visuals", "warn", "ai-hero-pill", "A pill / badge / announcement above the main heading (\"New\", \"Now live\", dot + label) — the most copied AI-template opener. Start with the headline; say it in the headline or the first paragraph.", ai.heroPills);
    if (ai.statusDots?.length) add("Visuals", "warn", "ai-status-dot", "Small green or pulsing status dots next to a label (\"Available\", \"Live\", \"Now open\") read as decoration. Keep them only for a real, live status in a product UI.", ai.statusDots);
    if (ai.accentBorders?.length) add("Visuals", "warn", "ai-accent-border", "Colored thick border on one side of a block (left or top accent bar) — a strong AI-template signature. Use a hairline all around, a background tint, or nothing.", ai.accentBorders);
    if (ai.iconTiles?.length >= 3) add("Visuals", "warn", "ai-icon-tile", `${ai.iconTiles.length} icons inside small tinted rounded squares — the default AI feature card. Show the icon bare, larger, or replace it with a real visual.`, ai.iconTiles.slice(0, 4));
    if (ai.gradientText?.length) add("Visuals", "warn", "ai-gradient-text", "Gradient-filled text. Use a solid ink color; emphasis through weight, size or a serif italic.", ai.gradientText);
    if (ai.glows?.length) add("Visuals", "warn", "ai-glow", "Large colored glow shadows behind elements. Use one neutral elevation system (border + soft layered shadow).", ai.glows);
    if (ai.centeredShare > 75) add("Visuals", "info", "ai-centered", `${ai.centeredShare}% of headings and paragraphs are centered; left-aligned editorial layouts read as more intentional.`);
  }

  // ---------- Responsive ----------
  if (!m.hasViewportMeta) add("Responsive", "error", "viewport-meta", 'Missing <meta name="viewport">.');
  if (m.overflowX > 1) add("Responsive", "error", "overflow", `Horizontal overflow of ${m.overflowX}px on mobile.`);
  const targets = m.interactive.filter((i) => !i.inline && i.width > 0);
  const isControl = (i) => i.tag !== "a";
  const tiny = targets.filter((i) => (i.width < 24 || i.height < 24) && isControl(i));
  if (tiny.length) add("Responsive", "error", "tap-target-min", "Controls under 24px (WCAG 2.2 target size minimum).", tiny.map((i) => `${i.sel} ${i.width}×${i.height}`));
  const small = targets.filter((i) => !tiny.includes(i) && i.height < 36 && (isControl(i) || i.height < 24));
  if (small.length > 2) add("Responsive", "warn", "tap-target", "Touch targets under 36px tall on mobile (44px is comfortable; standalone text links need ≥ 24px or spacing).", small.map((i) => `${i.sel} ${i.width}×${i.height}`));
  const tinyText = m.texts.filter((t) => t.fontSize < 12 && t.chars > 3);
  if (tinyText.length) add("Responsive", "warn", "tiny-text", "Text below 12px on mobile.", tinyText.map((t) => `${t.sel} ${t.fontSize}px "${t.text}"`));
  const smallBody = m.paragraphs.filter((p) => p.fontSize < 15);
  if (smallBody.length) add("Responsive", "warn", "mobile-body-size", "Paragraph text under 15px on mobile; use 16px.", smallBody.map((p) => `${p.sel} ${p.fontSize}px`));

  // ---------- Accessibility ----------
  const contrast = [...contrastIssues(d.texts), ...contrastIssues(m.texts)];
  const uniqueContrast = [...new Map(contrast.map((c) => [c.sel + c.ratio, c])).values()];
  if (uniqueContrast.length)
    add("Accessibility", uniqueContrast.length > 3 ? "error" : "warn", "contrast", "Text below WCAG AA contrast.", uniqueContrast.map((c) => `${c.sel} "${c.text}" ${c.ratio}:1 (needs ${c.required}:1)`));
  const noAlt = d.images.filter((i) => !i.hasAlt);
  if (noAlt.length) add("Accessibility", "error", "img-alt", "Images without an alt attribute.", noAlt.map((i) => i.src));
  const unlabeled = d.fields.filter((f) => !f.labelled);
  if (unlabeled.length) add("Accessibility", "error", "form-labels", "Form fields without a label.", unlabeled.map((f) => f.sel));
  const nameless = d.interactive.filter((i) => !i.hasName);
  if (nameless.length) add("Accessibility", "error", "accessible-name", "Interactive elements without an accessible name (icon buttons need aria-label).", nameless.map((i) => i.sel));
  if (!d.lang) add("Accessibility", "warn", "lang", "Missing lang attribute on <html>.");
  const levels = d.headings.map((h) => h.level);
  const skips = levels.filter((l, i) => i > 0 && l - levels[i - 1] > 1);
  if (skips.length) add("Accessibility", "warn", "heading-order", "Heading levels skip (e.g. h2 → h4).");

  const ax = d.a11y;
  if (ax) {
    if (ax.focusInvisible.length) add("Accessibility", ax.focusInvisible.length > 2 ? "error" : "warn", "focus-invisible", `Keyboard focus is not visible on ${ax.focusInvisible.length} of ${ax.focusChecked} controls checked (outline removed, nothing replaces it). Add a 2px ring with \`:focus-visible\`.`, ax.focusInvisible);
    if (ax.animated > 0 && !ax.reducedMotion) add("Accessibility", "warn", "reduced-motion", `${ax.animated} animated element(s) and no \`prefers-reduced-motion\` rule; turn animations off for people who ask for it.`);
  }

  return findings;
}

/** Score 1–5 per criterion from findings. Criteria that can't be fully measured are flagged. */
function score(findings) {
  const scores = {};
  for (const c of CRITERIA) {
    const penalty = findings.filter((f) => f.criterion === c).reduce((s, f) => s + PENALTY[f.severity], 0);
    scores[c] = Math.max(1, Math.round((5 - penalty) * 2) / 2);
  }
  const total = Object.values(scores).reduce((a, b) => a + b, 0);
  return { scores, total, max: CRITERIA.length * 5 };
}

/** Design-token summary useful for both audits and reference extraction. */
function summarizeTokens(data) {
  const byChars = new Map();
  for (const t of data.texts) byChars.set(t.fontFamily, (byChars.get(t.fontFamily) || 0) + t.chars);
  const totalChars = [...byChars.values()].reduce((a, b) => a + b, 0) || 1;
  const fonts = [...byChars.entries()].sort((a, b) => b[1] - a[1]).map(([f, c]) => ({ family: f, share: Math.round((c / totalChars) * 100) }));
  const typeScale = histogram(data.texts.map((t) => t.fontSize), Math.round).map(([s]) => s).sort((a, b) => b - a);
  const weights = histogram(data.texts.map((t) => t.fontWeight)).map(([w]) => w).sort((a, b) => a - b);
  const headings = data.headings.slice(0, 6).map((h) => ({
    level: h.level,
    fontSize: h.fontSize,
    letterSpacingEm: h.fontSize ? Math.round((h.letterSpacing / h.fontSize) * 1000) / 1000 : 0,
    lineHeight: h.lineHeight && h.fontSize ? Math.round((h.lineHeight / h.fontSize) * 100) / 100 : null,
    text: h.text,
  }));
  return {
    fonts,
    typeScale,
    weights,
    headings,
    spacing: histogram(data.spacing, Math.round).slice(0, 12).map(([v, c]) => ({ px: v, count: c })),
    gridConformity: Math.round(gridConformity(data.spacing) * 100),
    radii: histogram(data.radii).slice(0, 6).map(([v, c]) => ({ px: v, count: c })),
    shadows: histogram(data.shadows).slice(0, 4).map(([v, c]) => ({ value: v, count: c })),
  };
}

// ---- lib/probe.mjs ----
// In-page data collection. `collectPageData` is serialized and run inside the browser
// via page.evaluate, so it must stay self-contained (no imports, no outer variables).
// It only gathers raw measurements; all judgement happens in analyze.mjs (pure, testable).

function collectPageData() {
  const MAX = 4000;

  // Normalize any CSS color (rgb, hsl, oklch, color(), named…) to [r,g,b,a] through a canvas.
  const canvas = document.createElement("canvas");
  canvas.width = canvas.height = 1;
  const ctx = canvas.getContext("2d", { willReadFrequently: true });
  const cache = new Map();
  const rgba = (value) => {
    if (!value || value === "transparent") return [0, 0, 0, 0];
    if (cache.has(value)) return cache.get(value);
    ctx.clearRect(0, 0, 1, 1);
    ctx.fillStyle = "rgba(0,0,0,0)";
    ctx.fillStyle = value;
    ctx.fillRect(0, 0, 1, 1);
    const d = ctx.getImageData(0, 0, 1, 1).data;
    const out = [d[0], d[1], d[2], Math.round((d[3] / 255) * 1000) / 1000];
    cache.set(value, out);
    return out;
  };

  const selector = (el) => {
    if (el.id) return `${el.tagName.toLowerCase()}#${el.id}`;
    const cls = [...el.classList].filter((c) => !c.includes(":") && !c.includes("[")).slice(0, 2);
    const parent = el.parentElement ? el.parentElement.tagName.toLowerCase() + " > " : "";
    return parent + el.tagName.toLowerCase() + (cls.length ? "." + cls.join(".") : "");
  };

  const visible = (el) => {
    const r = el.getBoundingClientRect();
    if (r.width < 1 || r.height < 1) return false;
    const s = getComputedStyle(el);
    if (s.visibility === "hidden" || s.display === "none") return false;
    let n = el;
    while (n && n !== document.documentElement) {
      if (getComputedStyle(n).opacity === "0") return false;
      if (n.hasAttribute && (n.hasAttribute("hidden") || n.hasAttribute("inert") || n.getAttribute("aria-hidden") === "true")) return false;
      n = n.parentElement;
    }
    return true;
  };

  const srOnly = (el) => {
    const r = el.getBoundingClientRect();
    return r.width <= 1 && r.height <= 1;
  };

  // Background stack from the element up to the first opaque layer.
  const backgroundStack = (el) => {
    const layers = [];
    let hasImage = false;
    let n = el;
    while (n && n.nodeType === 1) {
      const s = getComputedStyle(n);
      if (s.backgroundImage && s.backgroundImage !== "none") hasImage = true;
      const c = rgba(s.backgroundColor);
      if (c[3] > 0) {
        layers.push(c);
        if (c[3] >= 1) break;
      }
      n = n.parentElement;
    }
    return { layers, hasImage };
  };

  const px = (v) => (v === "normal" ? null : parseFloat(v));

  // Number of rendered lines for an element's content (1 = no wrap).
  // Only text boxes count (icons and mixed font sizes on one baseline don't), and boxes that
  // overlap vertically belong to the same line.
  const lineCount = (el) => {
    const rects = [];
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    const range = document.createRange();
    for (let n = walker.nextNode(); n; n = walker.nextNode()) {
      if (!n.textContent.trim()) continue;
      range.selectNodeContents(n);
      for (const q of range.getClientRects()) if (q.width > 0 && q.height > 0) rects.push(q);
    }
    rects.sort((a, b) => a.top - b.top);
    let lines = 0;
    let bottom = -Infinity;
    for (const q of rects) {
      if (q.top >= bottom - 2) {
        lines++;
        bottom = q.bottom;
      } else bottom = Math.max(bottom, q.bottom);
    }
    return Math.max(1, lines);
  };
  const NUMBER = /^[\s+\-−–]*(?:[€$£]\s?)?[\d][\d\s.,\u00a0\u202f]*\s?(?:€|\$|£|%|k|K|M|x|×)?$/;
  const all = [...document.body.querySelectorAll("*")].slice(0, MAX);

  const texts = [];
  const spacing = [];
  const radii = [];
  const shadows = [];
  const clipped = [];
  for (const el of all) {
    if (["SCRIPT", "STYLE", "NOSCRIPT", "TEMPLATE"].includes(el.tagName.toUpperCase()) || el.closest("svg")) continue;
    if (!visible(el)) continue;
    const s = getComputedStyle(el);

    const ownText = [...el.childNodes]
      .filter((n) => n.nodeType === 3)
      .map((n) => n.textContent)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
    const disabled = el.closest(":disabled, [aria-disabled=true]");
    if (ownText && !srOnly(el) && !disabled) {
      const r = el.getBoundingClientRect();
      const bg = backgroundStack(el);
      texts.push({
        sel: selector(el),
        tag: el.tagName.toLowerCase(),
        text: ownText.slice(0, 60),
        chars: ownText.length,
        fontSize: px(s.fontSize),
        fontWeight: Number(s.fontWeight) || 400,
        lineHeight: px(s.lineHeight),
        letterSpacing: px(s.letterSpacing) ?? 0,
        fontFamily: s.fontFamily.split(",")[0].replace(/["']/g, "").trim(),
        color: rgba(s.color),
        opacity: Number(s.opacity),
        bgLayers: bg.layers,
        bgImage: bg.hasImage,
        width: Math.round(r.width),
        lines: ownText.length <= 40 ? lineCount(el) : null,
        isNumber: NUMBER.test(ownText),
      });
    }

    // Content pushed out of a scroll/clip container: only counts when real text is hidden.
    if (["auto", "scroll", "hidden", "clip"].includes(s.overflowX) && el.clientWidth > 0 && el.scrollWidth - el.clientWidth > 4) {
      const box = el.getBoundingClientRect();
      const hiddenText = [...el.querySelectorAll("*")].filter((c) => {
        if (!c.childNodes.length || ![...c.childNodes].some((n) => n.nodeType === 3 && n.textContent.trim())) return false;
        const q = c.getBoundingClientRect();
        return q.width > 0 && (q.left >= box.right - 1 || q.right > box.right + 8) && visible(c);
      });
      if (hiddenText.length)
        clipped.push({
          sel: selector(el),
          hiddenPx: el.scrollWidth - el.clientWidth,
          scrollable: s.overflowX === "auto" || s.overflowX === "scroll",
          examples: hiddenText.slice(0, 3).map((c) => c.textContent.replace(/\s+/g, " ").trim().slice(0, 30)),
          hiddenCount: hiddenText.length,
        });
    }

    for (const prop of ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft", "marginTop", "marginBottom", "rowGap", "columnGap"]) {
      const v = parseFloat(s[prop]);
      if (v > 0 && Number.isFinite(v)) spacing.push(Math.round(v * 100) / 100);
    }
    const rad = parseFloat(s.borderTopLeftRadius);
    if (rad > 0 && rad < 999) radii.push(Math.round(rad * 10) / 10);
    if (s.boxShadow && s.boxShadow !== "none") shadows.push(s.boxShadow);
  }

  const interactiveSel = "a[href], button, input:not([type=hidden]), select, textarea, summary, [role=button], [role=link], [role=tab], [role=radio], [onclick]";
  const interactive = [...document.querySelectorAll(interactiveSel)]
    .filter((el) => visible(el) || (el.tagName === "INPUT" && el.labels && el.labels.length))
    .map((el) => {
      // Visually hidden radio/checkbox: measure its visible label instead
      let box = el;
      if (el.tagName === "INPUT" && srOnly(el) && el.labels && el.labels[0]) box = el.labels[0];
      const r = box.getBoundingClientRect();
      const tag = el.tagName.toLowerCase();
      const parentText = el.parentElement ? el.parentElement.textContent.trim().length : 0;
      const inline = tag === "a" && getComputedStyle(el).display === "inline" && parentText > el.textContent.trim().length + 20;
      const name = (
        el.getAttribute("aria-label") ||
        el.getAttribute("aria-labelledby") ||
        el.getAttribute("title") ||
        el.textContent ||
        [...el.querySelectorAll("img[alt]")].map((i) => i.alt).join(" ") ||
        (el.labels && el.labels.length ? "label" : "") ||
        el.getAttribute("placeholder") ||
        el.value ||
        ""
      ).trim();
      const nativeInteractive = ["a", "button", "input", "select", "textarea", "summary"].includes(tag) || el.getAttribute("role");
      return {
        sel: selector(el),
        tag,
        width: Math.round(r.width),
        height: Math.round(r.height),
        inline,
        hasName: name.length > 0,
        clickableNonInteractive: el.hasAttribute("onclick") && !nativeInteractive,
        text: (el.textContent || "").replace(/\s+/g, " ").trim().slice(0, 40),
        lines: (el.textContent || "").trim().length && (el.textContent || "").trim().length <= 40 ? lineCount(el) : 1,
      };
    });

  const images = [...document.images].filter(visible).map((img) => {
    const r = img.getBoundingClientRect();
    const s = getComputedStyle(img);
    return {
      sel: selector(img),
      src: (img.currentSrc || img.src || "").slice(0, 120),
      hasAlt: img.hasAttribute("alt"),
      hasDimensions: img.hasAttribute("width") && img.hasAttribute("height"),
      broken: img.complete && img.naturalWidth === 0,
      naturalRatio: img.naturalWidth && img.naturalHeight ? img.naturalWidth / img.naturalHeight : null,
      renderedRatio: r.height ? r.width / r.height : null,
      objectFit: s.objectFit,
      format: ((img.currentSrc || img.src || "").split("?")[0].match(/\.(avif|webp|svg|png|jpe?g|gif)$/i) || [, (img.currentSrc || img.src || "").startsWith("data:image/") ? (img.currentSrc || img.src).slice(11, 15) : "unknown"])[1].toLowerCase(),
      naturalWidth: img.naturalWidth,
      renderedWidth: Math.round(r.width * (window.devicePixelRatio || 1)),
      lazy: img.loading === "lazy",
      belowFold: r.top + window.scrollY > window.innerHeight * 1.2,
    };
  });

  const fields = [...document.querySelectorAll("input:not([type=hidden]):not([type=submit]):not([type=button]), select, textarea")].map((el) => ({
    sel: selector(el),
    labelled: Boolean((el.labels && el.labels.length) || el.getAttribute("aria-label") || el.getAttribute("aria-labelledby") || el.getAttribute("title")),
  }));

  const headings = [...document.querySelectorAll("h1, h2, h3, h4, h5, h6")].filter(visible).map((h) => {
    const s = getComputedStyle(h);
    return {
      level: Number(h.tagName[1]),
      text: h.textContent.replace(/\s+/g, " ").trim().slice(0, 60),
      fontSize: parseFloat(s.fontSize),
      letterSpacing: px(s.letterSpacing) ?? 0,
      lineHeight: px(s.lineHeight),
    };
  });

  const paragraphs = [...document.querySelectorAll("p, li, blockquote, dd")]
    .filter((el) => visible(el) && el.textContent.trim().length > 90 && !el.querySelector("p, div, ul, ol, table"))
    .map((el) => {
      const s = getComputedStyle(el);
      const fs = parseFloat(s.fontSize);
      return {
        sel: selector(el),
        fontSize: fs,
        lineHeight: px(s.lineHeight),
        measure: Math.round(el.getBoundingClientRect().width / (fs * 0.5)),
      };
    });

  // ---------- Mobile interaction ----------
  const vpMeta = (document.querySelector('meta[name="viewport"]') || {}).content || "";
  const zoomBlocked = /user-scalable\s*=\s*(no|0)|maximum-scale\s*=\s*1(\.0+)?(?![\d.])/i.test(vpMeta);
  const smallInputs = [...document.querySelectorAll("input:not([type=hidden]):not([type=checkbox]):not([type=radio]):not([type=submit]):not([type=button]), select, textarea")]
    .filter(visible)
    .map((el) => ({ sel: selector(el), fontSize: parseFloat(getComputedStyle(el).fontSize) }))
    .filter((f) => f.fontSize < 16);

  const targetEls = [...document.querySelectorAll(interactiveSel)].filter((el) => visible(el) && !srOnly(el));
  const rects = targetEls.map((el) => ({ el, r: el.getBoundingClientRect() }));
  const crowded = [];
  for (let i = 0; i < rects.length && crowded.length < 40; i++) {
    const a = rects[i];
    if (a.r.width >= 44 && a.r.height >= 44) continue;
    if (a.el.tagName === "A" && getComputedStyle(a.el).display === "inline") continue;
    if (a.r.width >= 36 && a.r.height >= 36) continue;
    for (let j = 0; j < rects.length; j++) {
      if (i === j) continue;
      const b = rects[j];
      if (a.el.contains(b.el) || b.el.contains(a.el)) continue;
      const dx = Math.max(0, Math.max(a.r.left, b.r.left) - Math.min(a.r.right, b.r.right));
      const dy = Math.max(0, Math.max(a.r.top, b.r.top) - Math.min(a.r.bottom, b.r.bottom));
      if (Math.hypot(dx, dy) < 8) {
        if (crowded.some((c) => c.el === b.el && c.otherEl === a.el)) break;
        crowded.push({ el: a.el, otherEl: b.el });
        crowded[crowded.length - 1] = Object.assign(crowded[crowded.length - 1], { sel: selector(a.el), other: selector(b.el), gap: Math.round(Math.hypot(dx, dy)), text: (a.el.textContent || a.el.getAttribute("aria-label") || "").trim().slice(0, 24) });
        break;
      }
    }
  }

  for (const c of crowded) { delete c.el; delete c.otherEl; }
  const vpArea = window.innerWidth * window.innerHeight;
  const overlays = [];
  const touchBlockers = [];
  for (const el of all) {
    const s = getComputedStyle(el);
    if ((s.position === "fixed" || s.position === "sticky") && visible(el)) {
      const r = el.getBoundingClientRect();
      const w = Math.max(0, Math.min(r.right, window.innerWidth) - Math.max(r.left, 0));
      const h = Math.max(0, Math.min(r.bottom, window.innerHeight) - Math.max(r.top, 0));
      const coverage = (w * h) / vpArea;
      if (coverage > 0.2) overlays.push({ sel: selector(el), coverage: Math.round(coverage * 100), position: s.position });
    }
    if (s.touchAction === "none" && visible(el)) {
      const r = el.getBoundingClientRect();
      if ((r.width * r.height) / vpArea > 0.3) touchBlockers.push(selector(el));
    }
  }

  // Carousels / sliders: native scroll containers with several items, or known libraries
  const LIB = /swiper|slick|splide|glide|embla|flickity|keen-slider|owl-carousel|carousel|slider/i;
  const carousels = [];
  const seenCar = new Set();
  for (const el of all) {
    if (!visible(el) || seenCar.has(el)) continue;
    const s = getComputedStyle(el);
    const cls = typeof el.className === "string" ? el.className : "";
    const nativeScroll = (s.overflowX === "auto" || s.overflowX === "scroll") && el.children.length >= 3 && el.scrollWidth > el.clientWidth + 20 && !el.querySelector("table") && el.tagName !== "TABLE";
    const lib = LIB.test(cls) && el.children.length >= 2 && !LIB.test(el.parentElement && typeof el.parentElement.className === "string" ? el.parentElement.className : "");
    if (!nativeScroll && !lib) continue;
    [...el.querySelectorAll("*")].forEach((c) => seenCar.add(c));
    const scope = el.parentElement || el;
    const controls = [...scope.querySelectorAll("button, [role=button], a")].filter((b) => /prev|next|précédent|suivant|arrow|chevron|slide/i.test((b.getAttribute("aria-label") || "") + " " + (typeof b.className === "string" ? b.className : "") + " " + b.textContent));
    carousels.push({
      sel: selector(el),
      kind: nativeScroll ? "native" : "library",
      items: el.children.length,
      snap: s.scrollSnapType && s.scrollSnapType !== "none",
      controls: controls.length,
      namedControls: controls.filter((b) => (b.getAttribute("aria-label") || b.textContent || "").trim().length > 0).length,
      smallControls: controls.filter((b) => { const r = b.getBoundingClientRect(); return r.width < 32 || r.height < 32; }).length,
      indicators: Boolean(scope.querySelector('[role=tablist], [class*="dot"], [class*="pagination"], [class*="indicator"], [class*="bullet"]')),
      peek: nativeScroll ? el.scrollWidth > el.clientWidth : true,
    });
  }

  // ---------- Section rhythm (space between top-level blocks) ----------
  const mainEl = document.querySelector("main") || document.body;
  let blocks = [...mainEl.children];
  for (let depth = 0; depth < 3 && blocks.filter(visible).length < 2 && blocks.length === 1; depth++) blocks = [...blocks[0].children];
  const contentBox = (block) => {
    let top = Infinity, bottom = -Infinity;
    const bw = block.getBoundingClientRect().width;
    for (const c of block.querySelectorAll("*")) {
      if (c.closest("svg") && c.tagName.toLowerCase() !== "svg") continue;
      const own = [...c.childNodes].some((n) => n.nodeType === 3 && n.textContent.trim());
      const media = ["IMG", "SVG", "svg", "VIDEO", "CANVAS", "IFRAME", "INPUT", "BUTTON", "SELECT", "TEXTAREA", "PICTURE"].includes(c.tagName);
      const s = getComputedStyle(c);
      const painted = (s.backgroundColor && !/rgba\(0, 0, 0, 0\)|transparent/.test(s.backgroundColor)) || parseFloat(s.borderTopWidth) > 0;
      const r = c.getBoundingClientRect();
      // Full-width colored bands and dividers separate sections; they aren't content.
      if (!own && !media && (!painted || r.width >= bw * 0.95)) continue;
      if (r.width < 1 || r.height < 1) continue;
      top = Math.min(top, r.top + window.scrollY);
      bottom = Math.max(bottom, r.bottom + window.scrollY);
    }
    return top === Infinity ? null : { top, bottom };
  };
  const sectionGaps = [];
  const blockList = blocks.filter((b) => visible(b) && !["SCRIPT", "STYLE", "TEMPLATE"].includes(b.tagName) && b.getBoundingClientRect().height > 40);
  for (let i = 0; i < blockList.length - 1; i++) {
    const a = contentBox(blockList[i]);
    const b = contentBox(blockList[i + 1]);
    if (!a || !b) continue;
    sectionGaps.push({ between: [selector(blockList[i]), selector(blockList[i + 1])], gap: Math.round(b.top - a.bottom) });
  }

  // ---------- SEO ----------
  const meta = (name) => (document.querySelector(`meta[name="${name}"], meta[property="${name}"]`) || {}).content || "";
  const links = [...document.querySelectorAll("a[href]")];
  const mainText = ((document.querySelector("main") || document.body).innerText || "").trim();
  const seo = {
    title: document.title || "",
    description: meta("description"),
    canonical: (document.querySelector('link[rel="canonical"]') || {}).href || "",
    robots: meta("robots"),
    ogTitle: meta("og:title"),
    ogDescription: meta("og:description"),
    ogImage: meta("og:image"),
    twitterCard: meta("twitter:card"),
    jsonLd: document.querySelectorAll('script[type="application/ld+json"]').length,
    favicon: Boolean(document.querySelector('link[rel~="icon"]')),
    appleTouchIcon: Boolean(document.querySelector('link[rel="apple-touch-icon"]')),
    manifest: Boolean(document.querySelector('link[rel="manifest"]')),
    words: mainText ? mainText.split(/\s+/).length : 0,
    internalLinks: links.filter((a) => a.host === location.host).length,
    externalLinks: links.filter((a) => a.host && a.host !== location.host).length,
  };

  // ---------- Readability ----------
  const prose = [...document.querySelectorAll("p, li, dd, blockquote")].filter((el) => visible(el) && !el.querySelector("p, ul, ol, div"));
  const readability = prose
    .map((el) => {
      const t = el.innerText.replace(/\s+/g, " ").trim();
      const words = t ? t.split(" ").length : 0;
      const sentences = t.split(/[.!?…]+(?:\s|$)/).filter((x) => x.trim().split(" ").length > 2);
      const s = getComputedStyle(el);
      return {
        sel: selector(el),
        words,
        avgSentence: sentences.length ? Math.round(words / sentences.length) : words,
        justified: s.textAlign === "justify",
        uppercase: s.textTransform === "uppercase" && t.length > 40,
        fontSize: parseFloat(s.fontSize),
        text: t.slice(0, 50),
      };
    })
    .filter((p) => p.words >= 12);

  // ---------- "AI look" signals ----------
  const hue = ([r, g, b]) => {
    const R = r / 255, G = g / 255, B = b / 255;
    const max = Math.max(R, G, B), min = Math.min(R, G, B), d = max - min;
    if (d < 0.08) return null;
    let h = max === R ? ((G - B) / d) % 6 : max === G ? (B - R) / d + 2 : (R - G) / d + 4;
    return Math.round((h * 60 + 360) % 360);
  };
  const gradients = [];
  let glass = 0;
  const bigRadius = [];
  for (const el of all) {
    if (!visible(el)) continue;
    const s = getComputedStyle(el);
    if (s.backgroundImage.includes("gradient")) {
      const r = el.getBoundingClientRect();
      const colors = (s.backgroundImage.match(/(rgba?|hsla?|oklch|oklab|lab|lch|color)\([^()]*(\([^()]*\)[^()]*)*\)|#[0-9a-f]{3,8}\b/gi) || []).map(rgba).filter((c) => c[3] > 0.25);
      const hues = colors.map(hue).filter((h) => h !== null);
      const purple = hues.some((h) => h >= 255 && h <= 300);
      const blue = hues.some((h) => h >= 190 && h < 255);
      const pink = hues.some((h) => h > 300 && h <= 340);
      if ((r.width * r.height) / vpArea > 0.08 && purple && (blue || pink)) gradients.push(selector(el));
    }
    if (/blur\(/.test(s.backdropFilter || s.webkitBackdropFilter || "") && !["HEADER", "NAV"].includes(el.tagName) && !el.closest("header, nav")) glass++;
    const rad = parseFloat(s.borderTopLeftRadius);
    if (rad >= 24 && rad < 999 && el.getBoundingClientRect().width > 120) bigRadius.push(selector(el));
  }
  const EMOJI = /\p{Extended_Pictographic}/u;
  const emojiIn = [...document.querySelectorAll("h1, h2, h3, button, a")].filter((el) => visible(el) && EMOJI.test(el.textContent)).map((el) => `${selector(el)} "${el.textContent.trim().slice(0, 40)}"`);
  const CLICHE = /\b(transform(ez)? (your|votre|vos)|unlock (the|your)|revolutioni[sz]e|révolutionne[zr]?|elevate your|supercharge|seamless(ly)?|game[- ]changer|next[- ]level|take .{0,15} to the next level|boostez|propulsez|all[- ]in[- ]one solution|solution tout[- ]en[- ]un|in today'?s fast[- ]paced|dans un monde en constante évolution|cutting[- ]edge|innovative solutions?|solutions? innovantes?|empower(ing)? (your|you)|harness the power|unleash)\b/i;
  const cliches = [...document.querySelectorAll("h1, h2, h3, p")].filter((el) => visible(el) && CLICHE.test(el.textContent)).slice(0, 8).map((el) => `${selector(el)} "${el.textContent.replace(/\s+/g, " ").trim().slice(0, 60)}"`);
  // Rows of 3–4 identical "icon + title + text" cards
  const identicalCards = [];
  for (const parent of document.querySelectorAll("div, section, ul")) {
    const kids = [...parent.children].filter(visible);
    if (kids.length < 3 || kids.length > 4) continue;
    const sig = (k) => [...k.children].map((c) => c.tagName).join(",") + "|" + (typeof k.className === "string" ? k.className : "");
    const first = sig(kids[0]);
    if (!kids.every((k) => sig(k) === first)) continue;
    const iconTitleText = kids.every((k) => k.querySelector("svg, img, i, [class*=icon]") && k.querySelector("h3, h4, strong") && k.querySelector("p") && k.children.length <= 4);
    if (iconTitleText) identicalCards.push(selector(parent));
  }
  const chroma = ([r, g, b]) => Math.max(r, g, b) - Math.min(r, g, b);
  const painted = (c) => c[3] > 0.05;
  const h1 = [...document.querySelectorAll("h1")].find(visible);
  const heroPills = [];
  if (h1) {
    const h1r = h1.getBoundingClientRect();
    for (const el of document.querySelectorAll("a, span, div, p")) {
      if (el === h1 || el.contains(h1) || h1.contains(el) || !visible(el)) continue;
      const r = el.getBoundingClientRect();
      const txt = (el.textContent || "").replace(/\s+/g, " ").trim();
      if (!txt || txt.length > 70 || r.height > 44 || r.width < 40) continue;
      if (r.bottom > h1r.top + 4 || h1r.top - r.bottom > 140 || r.top < 0 || r.top > 700) continue;
      if (el.closest("header, nav")) continue;
      if (el.querySelector("p, h1, h2, h3, ul, button, img") ) continue;
      const s = getComputedStyle(el);
      const pill = parseFloat(s.borderTopLeftRadius) >= Math.min(r.height / 2, 999) - 1 && (painted(rgba(s.backgroundColor)) || parseFloat(s.borderTopWidth) > 0);
      const dot = [...el.querySelectorAll("span, i, svg")].some((d) => { const dr = d.getBoundingClientRect(); return dr.width > 0 && dr.width <= 12 && dr.height <= 12 && painted(rgba(getComputedStyle(d).backgroundColor)); });
      if (pill && !heroPills.some((x) => x.el.contains(el) || el.contains(x.el))) heroPills.push({ el, text: txt.slice(0, 40), dot });
    }
  }
  const heroPillOut = heroPills.slice(0, 3).map((x) => `${selector(x.el)} "${x.text}"${x.dot ? " (with dot)" : ""}`);
  const statusDots = [];
  const accentBorders = [];
  const iconTiles = [];
  const gradientText = [];
  const glows = [];
  for (const el of all) {
    if (!visible(el)) continue;
    const s = getComputedStyle(el);
    const r = el.getBoundingClientRect();
    if (r.width <= 12 && r.height <= 12 && r.width >= 4 && parseFloat(s.borderTopLeftRadius) >= r.width / 2 - 0.5) {
      const bg = rgba(s.backgroundColor);
      const h = painted(bg) ? hue(bg) : null;
      const green = h !== null && h >= 85 && h <= 170;
      const animated = s.animationName !== "none" && /ping|pulse|blink/i.test(s.animationName);
      const hasText = el.parentElement && (el.parentElement.textContent || "").trim().length > 2 && el.parentElement.getBoundingClientRect().height < 48;
      const ps = el.parentElement ? getComputedStyle(el.parentElement) : null;
      const inPill = ps && parseFloat(ps.borderTopLeftRadius) >= 8 && (painted(rgba(ps.backgroundColor)) || parseFloat(ps.borderTopWidth) > 0);
      if (hasText && !el.closest("td, th, tr, li, aside") && ((green && inPill && r.top < 900) || animated)) statusDots.push(`${selector(el)}${animated ? " (pulsing)" : ""} next to "${el.parentElement.textContent.replace(/\s+/g, " ").trim().slice(0, 30)}"`);
    }
    if (r.width > 120 && r.height > 40 && el.tagName !== "BLOCKQUOTE" && !el.closest("blockquote, nav, [role=tablist], table")) {
      const sides = ["Top", "Right", "Bottom", "Left"].map((k) => ({ k, w: parseFloat(s[`border${k}Width`]), c: rgba(s[`border${k}Color`]), st: s[`border${k}Style`] }));
      const thick = sides.filter((x) => x.w >= 2 && x.st !== "none" && painted(x.c) && chroma(x.c) > 40);
      const others = sides.filter((x) => x.w < 1 || x.st === "none");
      if (thick.length === 1 && others.length === 3 && thick[0].k !== "Bottom" && (el.textContent || "").trim().length > 10) accentBorders.push(`${selector(el)} (${thick[0].k.toLowerCase()} ${thick[0].w}px)`);
    }
    if (r.width >= 28 && r.width <= 64 && Math.abs(r.width - r.height) <= 2 && parseFloat(s.borderTopLeftRadius) > 0 && painted(rgba(s.backgroundColor)) && el.children.length === 1 && /^(svg|i|img)$/i.test(el.children[0].tagName) && !(el.textContent || "").trim() && el.tagName !== "BUTTON" && el.tagName !== "A" && !el.closest("button, a, nav, header")) iconTiles.push(selector(el));
    if ((s.backgroundClip === "text" || s.webkitBackgroundClip === "text") && s.backgroundImage.includes("gradient") && (el.textContent || "").trim()) gradientText.push(selector(el));
    if (s.boxShadow && s.boxShadow !== "none" && r.width > 80) {
      for (const m of s.boxShadow.matchAll(/(rgba?\([^)]*\)|oklch\([^)]*\)|color\([^)]*\))\s+(-?[\d.]+)px\s+(-?[\d.]+)px\s+([\d.]+)px/g)) {
        const c = rgba(m[1]);
        if (c[3] >= 0.2 && chroma(c) > 90 && parseFloat(m[4]) >= 20) { glows.push(selector(el)); break; }
      }
    }
  }
  const centered = [...document.querySelectorAll("h1, h2, h3, p")].filter(visible);
  const centeredShare = centered.length ? centered.filter((el) => getComputedStyle(el).textAlign === "center").length / centered.length : 0;

  const focusInvisible = [];
  const focusable = [...document.querySelectorAll("a[href], button, input:not([type=hidden]), select, textarea, summary, [tabindex]:not([tabindex='-1'])")].filter((el) => visible(el) && !srOnly(el) && !el.disabled && !el.closest("[inert]")).slice(0, 25);
  const prevFocus = document.activeElement;
  for (const el of focusable) {
    const look = () => { const s = getComputedStyle(el); return [s.outlineStyle, s.outlineWidth, s.outlineColor, s.boxShadow, s.borderTopColor, s.backgroundColor, s.textDecorationLine, s.color].join("|"); };
    const before = look();
    try { el.focus({ focusVisible: true, preventScroll: true }); } catch { el.focus(); }
    const after = look();
    const s = getComputedStyle(el);
    const outlined = s.outlineStyle !== "none" && parseFloat(s.outlineWidth) > 0 && rgba(s.outlineColor)[3] > 0;
    if (document.activeElement === el && before === after && !outlined) focusInvisible.push(selector(el));
    el.blur();
  }
  if (prevFocus && prevFocus.focus) prevFocus.focus();
  let reducedMotion = false;
  for (const sheet of document.styleSheets) {
    try { for (const rule of sheet.cssRules) if (rule.media && /prefers-reduced-motion/.test(rule.media.mediaText)) reducedMotion = true; } catch {}
  }
  const animated = all.filter((el) => { const s = getComputedStyle(el); return s.animationName !== "none" && parseFloat(s.animationDuration) > 0; }).length;

  const bodyText = document.body.innerText || "";
  return {
    url: location.href,
    viewport: { width: window.innerWidth, height: window.innerHeight },
    title: document.title,
    lang: document.documentElement.getAttribute("lang") || "",
    hasViewportMeta: Boolean(document.querySelector('meta[name="viewport"]')),
    hasDescription: Boolean(document.querySelector('meta[name="description"]')),
    overflowX: Math.max(0, document.documentElement.scrollWidth - document.documentElement.clientWidth),
    pageHeight: document.documentElement.scrollHeight,
    lorem: /lorem ipsum|dolor sit amet/i.test(bodyText),
    vagueLinks: interactive.filter((i) => /^(click here|here|read more|learn more|more|cliquez ici|en savoir plus)$/i.test(i.text)).length,
    texts,
    interactive,
    images,
    fields,
    headings,
    paragraphs,
    spacing,
    radii,
    shadows,
    clipped,
    rootFontSize: parseFloat(getComputedStyle(document.documentElement).fontSize),
    mobile: { zoomBlocked, smallInputs, crowded, overlays, touchBlockers, carousels },
    sectionGaps,
    seo,
    readability,
    a11y: { focusInvisible: focusInvisible.slice(0, 6), focusChecked: focusable.length, reducedMotion, animated },
    aiLook: { gradients, glass, bigRadius: bigRadius.length, bigRadiusSample: bigRadius.slice(0, 5), radiusElements: radii.length, emoji: emojiIn, cliches, identicalCards, heroPills: heroPillOut, statusDots: statusDots.slice(0, 5), accentBorders: accentBorders.slice(0, 6), iconTiles, gradientText: gradientText.slice(0, 4), glows: glows.slice(0, 4), centeredShare: Math.round(centeredShare * 100) },
  };
}

// ---- lib/report.mjs ----
// Human-readable audit report (pure — also bundled into audit.browser.js).

const ICON = { error: "✗", warn: "!", info: "·" };
const SHORT = { Hierarchy: "Hierarchy", Typography: "Typography", Spacing: "Spacing", Components: "Components", Visuals: "Visuals*", Content: "Content*", Responsive: "Responsive", Accessibility: "A11y", SEO: "SEO" };

/**
 * Format an audit result ({ target, scores, total, max, findings, tokens, note? }) like references/audit.md.
 * options.brief: one line per finding (rule id + first items), no explanations or token summary — for re-audits.
 * options.maxItems: offending elements listed per finding (default 4, brief 2).
 */
function formatReport(result, { brief = false, maxItems = brief ? 2 : 4 } = {}) {
  const lines = [];
  if (!brief) lines.push(`Automated audit — ${result.target}`);
  if (result.note) lines.push(result.note);
  lines.push(scoreLine(result));
  if (!brief) lines.push("(* partly measurable — confirm with a visual review of the screenshots)", "");
  const sorted = sortFindings(result.findings);
  if (!sorted.length) lines.push("No automated findings.");
  for (const f of sorted) {
    const total = f.count || f.items.length;
    const more = total > maxItems ? ` (+${total - Math.min(maxItems, f.items.length)} more)` : "";
    if (brief) {
      if (f.severity !== "info") lines.push(compactLine(f, maxItems));
      continue;
    }
    lines.push(`${ICON[f.severity]} [${f.criterion}] ${f.message}`);
    for (const item of f.items.slice(0, maxItems)) lines.push(`    ${item}`);
    if (more) lines.push(`   ${more}`);
  }
  if (brief) pushInfo(lines, sorted);
  const t = result.tokens;
  if (t && !brief) {
    lines.push("");
    lines.push("Measured tokens");
    lines.push(`  Fonts: ${t.fonts.map((f) => `${f.family} ${f.share}%`).join(", ")}`);
    lines.push(`  Type scale (px): ${t.typeScale.join(" / ")}`);
    lines.push(`  Spacing on 4px grid: ${t.gridConformity}% · most used: ${t.spacing.slice(0, 8).map((s) => s.px).join(", ")}`);
    lines.push(`  Radii (px): ${t.radii.map((r) => r.px).join(", ") || "none"}`);
  }
  return lines.join("\n");
}

/**
 * Compare a new audit with a saved baseline (--baseline before.json): score per criterion before → after,
 * fixed rules, and only what is still open or new. Much shorter than a full report on every iteration.
 */
function formatDelta(before, after, { maxItems = 2 } = {}) {
  const lines = [];
  const crit = CRITERIA.map((c) => {
    const a = before.scores?.[c];
    const b = after.scores[c];
    return a === undefined || a === b ? `${SHORT[c]} ${b}` : `${SHORT[c]} ${a}→${b}`;
  });
  lines.push(`Audit: ${crit.join(" · ")} → ${before.total}→${after.total}/${after.max}`);
  const beforeRules = new Set(before.findings.map((f) => f.rule));
  const afterRules = new Set(after.findings.map((f) => f.rule));
  const fixed = [...beforeRules].filter((r) => !afterRules.has(r));
  if (fixed.length) lines.push(`✓ fixed: ${fixed.join(", ")}`);
  const open = sortFindings(after.findings);
  if (!open.length) lines.push("No automated findings left.");
  for (const f of open) if (f.severity !== "info") lines.push(compactLine(f, maxItems, beforeRules.has(f.rule) ? "" : " NEW"));
  pushInfo(lines, open);
  return lines.join("\n");
}

function compactLine(f, maxItems, tag = "") {
  const total = f.count || f.items.length;
  const more = total > maxItems ? ` (+${total - Math.min(maxItems, f.items.length)} more)` : "";
  const items = f.items.slice(0, maxItems).join(" | ");
  return `${ICON[f.severity]}${tag} ${f.rule}${items ? `: ${items}${more}` : ""}`;
}

function pushInfo(lines, findings) {
  const info = findings.filter((f) => f.severity === "info").map((f) => f.rule);
  if (info.length) lines.push(`· info: ${info.join(", ")}`);
}

function scoreLine(result) {
  return "Audit: " + CRITERIA.map((c) => `${SHORT[c]} ${result.scores[c]}`).join(" · ") + ` → ${result.total}/${result.max}`;
}

function sortFindings(findings) {
  const order = { error: 0, warn: 1, info: 2 };
  return [...findings].sort((a, b) => order[a.severity] - order[b.severity]);
}

const data = collectPageData();
const findings = analyze(data, data);
const result = {
  target: location.href,
  note: "Viewport: " + innerWidth + "px (single-viewport audit — rerun at 390px for mobile checks)",
  ...score(findings),
  findings,
  tokens: summarizeTokens(data),
};
const report = formatReport(result);
console.log(report);
return { report, result };
})();
